### ISSUE TITLE
How can I get the file "entries.npy" for training Imagenet22K

### ISSUE THREAD

**Issue by XiaohuJoshua** [facebookresearch/dinov2#100]
When I implement codes like:
```
from dinov2.data.datasets import ImageNet22k
dataset = ImageNet(split=split, root="<ROOT>", extra="<EXTRA>")
dataset.dump_extra()
```
I got error like: "No such file or directory: 'entries.npy'"

**Comment by XiaohuJoshua** [comment]
And how can I add my own datasets for training. Thanks

**Comment by patricklabatut** [comment]
@XiaohuJoshua Will try to update the code and documentation to facilitate plugging custom datasets and generating the required metadata for ImageNet22k (similar to #60).

**Comment by EddieAy** [comment]
> @XiaohuJoshua Will try to update the code and documentation to facilitate plugging custom datasets and generating the required metadata for ImageNet22k (similar to #60).

So can we train with our dataset now? I still can't get these files

**Comment by patricklabatut** [comment]
Closing, tracked in #243

**Comment by shashankvkt** [comment]
@XiaohuJoshua have you solved this problem? I still get the same error. I do the following:
```
from dinov2.data.datasets.image_net_22k import ImageNet22k
dataset = ImageNet22k(root=root_path, extra=extra_path)
dataset.dump_extra()
```
do you change anything in your implementation?
