### ISSUE TITLE
Potential Bug on Loss Centering

### ISSUE THREAD

**Issue by jacklishufan** [facebookresearch/dinov2#113]
https://github.com/facebookresearch/dinov2/blob/main/dinov2/train/ssl_meta_arch.py#LL213C17-L213C17 

Why are there `masked_teacher_patch_tokens_after_head[:n_masked_patches]` when masked_teacher_patch_tokens_after_head is guaranteed to have size 1 at dim 0 (unsqueeze at L208)?  should it be `masked_teacher_patch_tokens_after_head[:, :n_masked_patches]` as L210.

**Comment by qasfb** [comment]
There is a .squeeze(0) in the line right above the one you pointed to, therefore the first dimension is removed is removed in this case. Does that make sense ?

**Comment by patricklabatut** [comment]
Closing as answered.

**Comment by zhiyuanyou** [comment]
Hello, although you mention `.squeeze(0)`, however, it is in `masked_teacher_ibot_softmaxed_centered`, not in `masked_teacher_patch_tokens_after_head`. So there still maybe be something wrong within this line. 

```
                if do_ibot:
                    masked_teacher_patch_tokens_after_head = masked_teacher_patch_tokens_after_head.unsqueeze(0)
                    masked_teacher_ibot_softmaxed_centered = self.ibot_patch_loss.softmax_center_teacher(
                        masked_teacher_patch_tokens_after_head[:, :n_masked_patches], teacher_temp=teacher_temp
                    )
                    masked_teacher_ibot_softmaxed_centered = masked_teacher_ibot_softmaxed_centered.squeeze(0)
                    self.ibot_patch_loss.update_center(masked_teacher_patch_tokens_after_head[:n_masked_patches])
```
