### ISSUE TITLE
Same input, same model, different feature output (PyTorch 2.0)

### ISSUE THREAD

**Issue by chenshihfang** [facebookresearch/dinov2#115]
Hi, I refer to the inference code from [here](https://github.com/facebookresearch/dinov2/issues/2).

But I found that, given the same input, it produces different output.

<img width="339" alt="image" src="https://github.com/facebookresearch/dinov2/assets/113094161/03ad2cbd-0144-4838-bc97-84f6276a9d7d">

Does anyone know why this happens?

I use the manual seed already, and it still happens.
Inference under PyTorch 2.0

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.22.4
[pip3] torch==2.0.0+cu117
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchmetrics==0.10.3
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.0+cu117
[pip3] triton==2.0.0
[conda] Could not collect

**Comment by fepegar** [comment]
@sfchen94 Did you figure out why this was happening?

**Comment by benam2** [comment]
@sfchen94 could you please share how did you fix your issue?

**Comment by QitaoZhao** [comment]
Same issue here
