### ISSUE TITLE
How can DINOv2 takes image with different shape as input when inference?

### ISSUE THREAD

**Issue by Leon1207** [facebookresearch/dinov2#118]
If I have an image with a shape of 240*320, what should I do to generate the mask with same shape before and after passing the image to the pertrain DINOv2? Thanks!

**Comment by nharada1** [comment]
Your image must be a multiple of the patch size on each dimension. In the case of DINO, this means it must be an even multiple of 14 -- try resizing the image to 238x322

**Comment by Leon1207** [comment]
Thanks for your advice!

**Comment by patricklabatut** [comment]
> Your image must be a multiple of the patch size on each dimension. In the case of DINO, this means it must be an even multiple of 14 -- try resizing the image to 238x322

Yes, exactly and see the last sentences of the "Model Details" section: https://github.com/facebookresearch/dinov2/blob/main/MODEL_CARD.md#model-details for reference. Closing as resolved.
