### ISSUE TITLE
Model distillation code and sharing full weights (including iBOT and DINO heads)

### ISSUE THREAD

**Issue by usryokousha** [facebookresearch/dinov2#119]
Model distillation as presented in the paper is not implemented in this repository.  Additionally, to allow for distillation the full weights of the original model should be made available.  This would include the DINO and iBOT head weights (separate heads were used to train ViT-G as reflected in the config).

I personally would like to use knowledge distillation to train a lighter model with similar performance, but rather extend to a different modality.

The code as found in **dinov2/train/ssl_meta_arch.py** could be modified to enable distillation with some minor changes.  This would include the shadow copy of the student, a different head for the student (assuming the embed_dim is different), an ema update method, etc.

 I have started working on this code in a [fork](https://github.com/usryokousha/dinov2/blob/main/dinov2/train/distill_meta_arch.py) of this repository.  Should I just file it as a pull request?  It would be nice if the original implementation / working implementation was available here.

**Comment by usryokousha** [comment]
I think it was clear based on previous issues there was clear intention not to release the full weights.

**Comment by nemonameless** [comment]
so why not to release the full weights and full training codes ?
@usryokousha Can your codes be trained and reproduce the training results?
