### ISSUE TITLE
Finetuning with custom dataset

### ISSUE THREAD

**Issue by m00yu** [facebookresearch/dinov2#126]
Hello, thanks for great work!

I wanted to compare DINO-v1 and DINO-v2 with my custom dataset, but I think it is not possible to train DINO-v2 with the custom dataset in the current code.
In DINO-v1, it was possible to load the checkpoint and fine-tune the model with my current dataset.

This is the code in DINO-v2 and only ImageNet data can be trained...😥
![image](https://github.com/facebookresearch/dinov2/assets/113628931/9072a1d1-3b7e-47b8-94aa-20b5dd2174d8)

Is there any way to train DINO-v2 with my custom dataset? 

I saw the issue https://github.com/facebookresearch/dinov2/issues/72 but this was about 'how to train general ViT with custom dataset', not with DINO-v2.

Can anyone share own trials about this issue?

Thank you!

**Comment by MohammedSB** [comment]
Hey! 
You should be able to train using a custom dataset if you make a new class for that dataset, following the standards in those ImageNet classes. If you are not going to use ImageNet, you could also change those standards (how folder should be organized, etc.) to fit your own purposes.

**Comment by patricklabatut** [comment]
Closing, tracked in #243
