### ISSUE TITLE
Documentation on Inference

### ISSUE THREAD

**Issue by 1ssb** [facebookresearch/dinov2#127]
Hi, I am very much new to this and just exploring dinov2. Is it kindly possible to release a step by step documentation to run inference for semantic segmentation on a single image or better a video?

**Comment by woctezuma** [comment]
- #1

**Comment by 1ssb** [comment]
I prepared a self styled code for Webcam Dinov2, note the change in environment as an image in Linux. https://github.com/1ssb/webcamdino/edit/main/fuser.py
