### ISSUE TITLE
[request] Release under a more permissive license (e.g. Apache 2.0)

### ISSUE THREAD

**Issue by giacomov** [facebookresearch/dinov2#128]
The original DINO and the more modern SAM both have a ~~GPL-2.0~~ Apache 2.0 license which allows the use within commercial applications.

Why is DINOv2 CC-4.0 instead? That limits any application of this research in industrial settings, which is a pity.

**Comment by patricklabatut** [comment]
> The original DINO and the more modern SAM both have a GPL-2.0 license which allows the use within commercial applications.

I believe you meant an Apache 2.0 license instead instead of CC-BY-NC. GPL would actually bring restrictions that would deter many applications.

> Why is DINOv2 CC-4.0 instead?

This was the easiest to get within the tight time frame of the release. We are well aware of the corresponding limitations, but please stay tuned.

**Comment by hayk-skydio** [comment]
@patricklabatut very much looking forward to hearing about any options for commercial use. Can you let us know if there's a plan there?

**Comment by giacomov** [comment]
Yes, sorry, I did mean Apache 2.0. I hope this will get changed soon, don't hesitate to ask if you need anything from me to speed this up (like a description of a use case, for example).
