### ISSUE TITLE
Correct order of dimensions of input tensor

### ISSUE THREAD

**Issue by TedLentsch** [facebookresearch/dinov2#132]
I have studied the source code of the DinoVisionTransformer model and the torchvision implementation of VisionTransformer. I notice that the shape of input tensor ``x`` is interpreted differently. Therefore, I wonder what the correct input shape of DinoVisionTransformer model is. So is this (B,C,H,W) or (B,C,W,H)? The implementation of DinoVisionTransformer model suggests (B,C,W,H), while the torchvision implementation of VisionTransformer uses (B,C,H,W). This does matter for the patch embedding (otherwise the input images are rotated with respect to the kernels of the 2D convolution of the patch embedding).

Line 192 of the file vision_transformer.py (commit fc49f49) states ``B, nc, w, h = x.shape``, see https://github.com/facebookresearch/dinov2/blob/main/dinov2/models/vision_transformer.py#L192.

Line 269 of the torchvision source code (commit 683baf8) states ``n, c, h, w = x.shape``, see https://github.com/pytorch/vision/blob/main/torchvision/models/vision_transformer.py#L269.

**Comment by qasfb** [comment]
This is a reasonable catch, but it should matter only for rectangular images, which we haven't tested too much.
Though, I believe it can only have an effect within the interpolate_pos_encoding function; but as long as the (w,h) ordering is  consistent all the way until reaching the nn.functional.interpolate function, it should be fine. Does that make sense ?

https://github.com/facebookresearch/dinov2/blob/main/dinov2/models/vision_transformer.py#L165-L189
