### ISSUE TITLE
Hidden features in SwiGLUFFNFused

### ISSUE THREAD

**Issue by adamcasson** [facebookresearch/dinov2#133]
Hi, I'm curious as to why the number of hidden features is modified as such in the fused swiglu ffn here: https://github.com/facebookresearch/dinov2/blob/c3c2683a13cde94d4d99f523cf4170384b00c34c/dinov2/layers/swiglu_ffn.py#L57

when trying to make ViT-B (mlp ratio 4) this results in:

```
(mlp): SwiGLUFFNFused(
    (w12): Linear(in_features=768, out_features=4096, bias=True)
    (w3): Linear(in_features=2048, out_features=768, bias=True)
)
```
which seems like an mlp ratio of 2.67

whereas the pytorch swiglu ffn class gives the expected mlp ratio of 4:

```
(mlp): SwiGLUFFN(
    (w12): Linear(in_features=768, out_features=6144, bias=True)
    (w3): Linear(in_features=3072, out_features=768, bias=True)
)
```

**Comment by adamcasson** [comment]
realizing now that modifying feature size in fused swiglu might be to achieve the same amount of params as a standard ViT with non-swiglu ffn. i.e.:

```
swiglu mlp ffn params  = 768 * 4096 + 2048 * 768 = 4,718,592
regular mlp ffn params = 768 * 3072 + 3072 * 768 = 4,718,592
```

**Comment by wangh09** [comment]
Thanks Adam
