### ISSUE TITLE
Pixel-level representations with DINOv2

### ISSUE THREAD

**Issue by YScheung** [facebookresearch/dinov2#139]
Hi. In a lot of research papers, I have read that DINOv2 can generate pixel-level representations. Could anyone let me know how I could obtain that as the features I have right now are patch-based. Many thanks.

**Comment by Chuan-10** [comment]
Hi, I have the same question, have u found some methods?

**Comment by KindofCrazy** [comment]
@Chuan-10  Hello! I am still confused about how to get pixel-level feature. Have you got some methods?
