### ISSUE TITLE
Will the other heads be released (eg. depth estimation)

### ISSUE THREAD

**Issue by eware-godaddy** [facebookresearch/dinov2#14]
Currently, on the base models have been released, and an imagenet layer. Are there plans to release the other heads that were mentioned in the paper? (eg. depth estimation, segmentation, etc).

**Comment by patricklabatut** [comment]
Thanks for your interest! That request is related to #6 and we are monitoring feedback to possibly provide more pointers or helpers to reproduce the results, including depth estimation and segmentation.

**Comment by patricklabatut** [comment]
Closing to use #54 to keep track feedback on documentation, training code or model weights for depth.

**Comment by patricklabatut** [comment]
We have just added the models and supporting code for semantic segmentation and depth estimation.
