### ISSUE TITLE
How to do image feature extractions?

### ISSUE THREAD

**Issue by linkhochon** [facebookresearch/dinov2#15]
Hi there!

Is there any documentation or guide on how to use this model as a feature extractor? 
I'd like to feed it some images and receive features of those images. 

Thanks.

**Comment by patricklabatut** [comment]
No, but that's something we will definitely consider documenting better. Meanwhile I would point you the evaluation code available under `dinov2/eval/` which does extract (and combine) features to feed them into simple classifiers.

**Comment by woctezuma** [comment]
Related:
- #2

**Comment by linkhochon** [comment]
I'll check them out. Thank you both @woctezuma and @patricklabatut! 
And looking forward to read the documentation once it's available. It'd be very informative!  Thanks again :)

**Comment by patricklabatut** [comment]
Closing this specific issue and keeping #2 open until the documentation is improved.

**Comment by MengHao666** [comment]
> Closing this specific issue and keeping [#2](https://github.com/facebookresearch/dinov2/issues/2) open until the documentation is improved.

where is the document? so far I could not find the official instructions to extract image features from dino v2. I feel upset.
