### ISSUE TITLE
xFormers not available

### ISSUE THREAD

**Issue by byte-dance** [facebookresearch/dinov2#151]
when I run the following code: 
dinov2_vits14 = torch.hub.load('facebookresearch/dinov2', 'dinov2_vits14')
dinov2_vitb14 = torch.hub.load('facebookresearch/dinov2', 'dinov2_vitb14')
dinov2_vitl14 = torch.hub.load('facebookresearch/dinov2', 'dinov2_vitl14')
dinov2_vitg14 = torch.hub.load('facebookresearch/dinov2', 'dinov2_vitg14')
the python console prints 
'xFormers not available'
'xFormers not available',
what should I do to solve it?

**Comment by byte-dance** [comment]
Is it ok to just omit this info?

**Comment by patricklabatut** [comment]
This warning comes from [there](https://github.com/facebookresearch/dinov2/blob/main/dinov2/layers/block.py#L32).

> Is it ok to just omit this info?

While using the [xFormers](https://github.com/facebookresearch/xformers) library is recommended (even for inference only on the right platforms), this is just a warning and it can be ignored.

**Comment by patricklabatut** [comment]
Closing as answered.
