### ISSUE TITLE
Will OCR be possible?

### ISSUE THREAD

**Issue by FarisHijazi** [facebookresearch/dinov2#18]
I want to use this as a general purpose backbone for multiple downstream taskw, dors it already perform well on OCR and text recognition tasks?

**Comment by patricklabatut** [comment]
Hi and thanks for your interest in using DINOv2! No, all the visual tasks on which we had evaluation results are listed in paper and we haven't tried (yet) OCR / text recognition tasks. But if you try, please share back your experience.
