### ISSUE TITLE
Is this the right way to do inference?

### ISSUE THREAD

**Issue by Suhail** [facebookresearch/dinov2#2]
I presume I don't need Normalize?

![CleanShot 2023-04-17 at 12 39 54](https://user-images.githubusercontent.com/66225/232593036-3f636562-b648-4b19-a538-9fb4be99c94c.png)

**Comment by Esbenthorius** [comment]
Not sure if its correct, but hope it helps

`import torch
from PIL import Image
import torchvision.transforms as T
import hubconf

# dinov2_vits14 = torch.hub.load('facebookresearch/dinov2', 'dinov2_vits14')
dinov2_vits14 = hubconf.dinov2_vits14()

# Load image
img = Image.open('meta_dog.png')

# Preprocess image
transform = T.Compose([
    T.Resize(224),
    T.CenterCrop(224),
    T.ToTensor(),
    T.Normalize(mean=[0.5], std=[0.5]),
])

img = transform(img)[:3].unsqueeze(0)

# Inference
with torch.no_grad():
    features  = dinov2_vits14(img, return_patches=True)[0]

# Features are of shape [1, 384]
print(features.shape)
#Visualization of the three first principal components of the patch features of all frames, mapped to RGB values.
import matplotlib.pyplot as plt
import numpy as np
from sklearn.decomposition import PCA

# Compute PCA
pca = PCA(n_components=3)
pca.fit(features)

# Map to RGB
pca_features = pca.transform(features)
pca_features = (pca_features - pca_features.min()) / (pca_features.max() - pca_features.min())
pca_features = pca_features * 255

# Plot
plt.imshow(pca_features.reshape(16, 16, 3).astype(np.uint8))
plt.savefig('meta_dog_features.png')`

In dinov2/models/vision_transformer.py line 290 add 

`    def forward(self, *args, is_training=False, return_patches=False, **kwargs):
        ret = self.forward_features(*args, **kwargs)
        if is_training:
            return ret
        elif return_patches:
            return ret["x_norm_patchtokens"]
        else:
            return self.head(ret["x_norm_clstoken"])
`
input:
<img width="248" alt="meta_dog" src="https://user-images.githubusercontent.com/48384848/232604774-830adc36-6bf1-4fa3-8fbf-3d54e6376b28.png">

visualized features:

![meta_dog_features](https://user-images.githubusercontent.com/48384848/232604731-ad7388e0-ce7a-4ef4-be49-6cb9e761e829.png)

**Comment by patricklabatut** [comment]
@Suhail To generate features from the pretrained backbones, just use a transform similar to the standard one used for evaluating on image classification with the typical ImageNet normalization mean and std (see [what's used in the code](https://github.com/facebookresearch/dinov2/blob/main/dinov2/data/transforms.py#L78)). Also, as noted in the model card, the model can also use image sizes that are multiple of the patch size.

**Comment by Suhail** [comment]
> @Suhail To generate features from the pretrained backbones, just use a transform similar to the standard one used for evaluating on image classification with the typical ImageNet normalization mean and std (see [what's used in the code](https://github.com/facebookresearch/dinov2/blob/main/dinov2/data/transforms.py#L78)). Also, as noted in the model card, the model can also use image sizes that are multiple of the patch size.

Thanks! This is what I used:
```py
image_transforms = T.Compose([
    T.Resize(256, interpolation=T.InterpolationMode.BICUBIC),
    T.CenterCrop(224),
    T.ToTensor(),
    T.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
])
```

Let me know if that's wrong though.

**Comment by Suhail** [comment]
> ```python
> T.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
> ```

Sounds like we should be using the ImageNet normalization: `T.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),`

**Comment by jjennings955** [comment]
> Not sure if its correct, but hope it helps
> 
> import torch from PIL import Image import torchvision.transforms as T import hubconf
> 
> dinov2_vits14 = hubconf.dinov2_vits14()
> 
> img = Image.open('meta_dog.png')
> 
> transform = T.Compose([ T.Resize(224), T.CenterCrop(224), T.ToTensor(), T.Normalize(mean=[0.5], std=[0.5]), ])
> 
> img = transform(img)[:3].unsqueeze(0)
> 
> with torch.no_grad(): features = dinov2_vits14(img, return_patches=True)[0]
> 
> print(features.shape) import matplotlib.pyplot as plt import numpy as np from sklearn.decomposition import PCA
> 
> pca = PCA(n_components=3) pca.fit(features)
> 
> pca_features = pca.transform(features) pca_features = (pca_features - pca_features.min()) / (pca_features.max() - pca_features.min()) pca_features = pca_features * 255
> 
> plt.imshow(pca_features.reshape(16, 16, 3).astype(np.uint8)) plt.savefig('meta_dog_features.png')
> 
> In dinov2/models/vision_transformer.py line 290 add
> 
> def forward(self, *args, is_training=False, return_patches=False, **kwargs): ret = self.forward_features(*args, **kwargs) if is_training: return ret elif return_patches: return ret["x_norm_patchtokens"] else: return self.head(ret["x_norm_clstoken"])
> 
> input: <img alt="meta_dog" width="248" src="https://user-images.githubusercontent.com/48384848/232604774-830adc36-6bf1-4fa3-8fbf-3d54e6376b28.png">
> 
> visualized features:
> 
> ![meta_dog_features](https://user-images.githubusercontent.com/48384848/232604731-ad7388e0-ce7a-4ef4-be49-6cb9e761e829.png)

I found this helpful, but I would say instead of needing to modify the forward function, you can just do `dino.forward_features(x)["x_norm_patchtokens"]` yourself directly.

**Comment by Suhail** [comment]
> > > @Suhail To generate features from the pretrained backbones, just use a transform similar to the standard one used for evaluating on image classification with the typical ImageNet normalization mean and std (see [what's used in the code](https://github.com/facebookresearch/dinov2/blob/main/dinov2/data/transforms.py#L78)). Also, as noted in the model card, the model can also use image sizes that are multiple of the patch size.
> 
> > 
> 
> > Thanks! This is what I used:
> 
> > 
> 
> > ```python
> 
> > image_transforms = T.Compose([
> 
> >     T.Resize(256, interpolation=T.InterpolationMode.BICUBIC),
> 
> >     T.CenterCrop(224),
> 
> >     T.ToTensor(),
> 
> >     T.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
> 
> > ])
> 
> > ```
> 
> > 
> 
> > Let me know if that's wrong though.
> 
> 
> 
> What you are doing is correct. What you get with the `forward` method is the CLS token. If you'd like the patch tokens, you can use `forward_features`, as noted by @jjennings955 

I think what I want is an embedding like CLIP that contains the features/understanding of the image. Is that what I'd get from forward_features?

**Comment by woctezuma** [comment]
If this is like DINO, any of the two features could be used as an image embedding.

**Comment by woctezuma** [comment]
Please note that `linear.py` adopts a different approach. It was also the case with DINO.

See:

https://github.com/facebookresearch/dinov2/blob/fc49f49d734c767272a4ea0e18ff2ab8e60fc92d/dinov2/eval/linear.py#L503-L507

https://github.com/facebookresearch/dinov2/blob/fc49f49d734c767272a4ea0e18ff2ab8e60fc92d/dinov2/eval/utils.py#L31-L45

**Comment by Elsword016** [comment]
How about this??
 `img = Image.open('')
transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),  ])
 input_tensor = transform(img)
input_batch = input_tensor.unsqueeze(0).cuda()
with torch.no_grad():
    output =dinov2_vits14.get_intermediate_layers(input_batch)`

the output is a tuple  of intermediate feature maps. Then you can select which features you want from the tuple, and then you can try K-means etc etc

**Comment by woctezuma** [comment]
Yes, `get_intermediate_layers()` allows different approchaes. This is similar to what is done in `linear.py` as mentioned above.

**Comment by Suhail** [comment]
Sounds like this is all I need to do to get a features embedding: `dino_emb = dinov2_vitg14(t_img.unsqueeze(0))`

**Comment by patricklabatut** [comment]
Closing as this seems resolved (and using #53 to keep track of documentation needs on feature extraction).

**Comment by aaiguy** [comment]
hello, How to train nearest neighbors model on extracted embeddings of images from different classes of folders  using dinov2 model and retrieve nearest  similar image for query image ? 
I tried below approach using sklearn nearest neighbors 

```
import torch
from sklearn.neighbors import NearestNeighbors 
import pickle
from PIL import Image
import torchvision.transforms as T
import os 
# import hubconf
import tqdm
from tqdm import tqdm_notebook
device = torch.device('cuda' if torch.cuda.is_available() else "cpu")
print('device:',device)
# dinov2_vits14 = hubconf.dinov2_vits14()
dinov2_vits14 = torch.hub.load('facebookresearch/dinov2', 'dinov2_vitg14')
dinov2_vits14.to(device)
def extract_features(filename):
    img = Image.open(filename)

    transform = T.Compose([
    T.Resize(224),
    T.CenterCrop(224),
    T.ToTensor(),
    T.Normalize(mean=[0.5], std=[0.5]),
    ])

    img = transform(img)[:3].unsqueeze(0)

    with torch.no_grad():
        features = dinov2_vits14(img.to('cuda'))[0]

    # print(features.shape)
    return features.numpy()

extensions = ['.jpg', '.JPG', '.jpeg', '.JPEG', '.png', '.PNG']

def get_file_list(root_dir):
    file_list = []
    for root, directories, filenames in os.walk(root_dir):
        for filename in filenames:
            if any(ext in filename for ext in extensions):
                filepath = os.path.join(root, filename)
                if os.path.exists(filepath):
                  file_list.append(filepath)
                else:
                  print(filepath)
    return file_list
def extract_features(filename):
    img = Image.open(filename)

    transform = T.Compose([
    T.Resize(224),
    T.CenterCrop(224),
    T.ToTensor(),
    T.Normalize(mean=[0.5], std=[0.5]),
    ])

    img = transform(img)[:3].unsqueeze(0)

    with torch.no_grad():
        features = dinov2_vits14(img.to('cuda'))[0]

    # print(features.shape)
    return features.cpu().numpy()

extensions = ['.jpg', '.JPG', '.jpeg', '.JPEG', '.png', '.PNG']

def get_file_list(root_dir):
    file_list = []
    for root, directories, filenames in os.walk(root_dir):
        for filename in filenames:
            if any(ext in filename for ext in extensions):
                filepath = os.path.join(root, filename)
                if os.path.exists(filepath):
                  file_list.append(filepath)
                else:
                  print(filepath)
    return file_list

# # path to the your datasets
root_dir = 'image_folder' 
filenames = sorted(get_file_list(root_dir))
print('Total files :', len(filenames))
feature_list = []
for i in tqdm.tqdm(range(len(filenames))):
    feature_list.append(extract_features(filenames[i]))
pickle.dump(feature_list,open('dino-all-feature-list.pickle','wb'))
pickle.dump(filenames,open('dino-all-filenames.pickle','wb'))
neighbors = NearestNeighbors(n_neighbors=5, algorithm='brute',metric='euclidean').fit(feature_list)
# Save the model to a file
with open('dino-all-neighbors2.pkl', 'wb') as f:
    pickle.dump(neighbors, f)
```
with above dinov2 based trained   model i get around 70% accuracy on  testing data for retrieving similar class images, is there a way to improve my approach in better manner to improvise  the accuracy ??

**Comment by woctezuma** [comment]
For [k-NN classification](https://github.com/facebookresearch/dinov2#k-nn-classification-on-imagenet-1k), see [`knn.py`](https://github.com/facebookresearch/dinov2/blob/main/dinov2/eval/knn.py).

With a quick look at your code, I would suggest to try a different metric, e.g. `cosine` instead of `euclidean`.

**Comment by aaiguy** [comment]
hey thanks, i will look into it. 
where can I find the cv.transform used for DINOv2 one?

**Comment by woctezuma** [comment]
> hey thanks, i will look into it. where can I find the cv.transform used for DINOv2 one?

It is mentioned above: https://github.com/facebookresearch/dinov2/issues/2#issuecomment-1512068038

**Comment by aaiguy** [comment]
> Not sure if its correct, but hope it helps
> 
> import torch from PIL import Image import torchvision.transforms as T import hubconf
> 
> dinov2_vits14 = hubconf.dinov2_vits14()
> 
> img = Image.open('meta_dog.png')
> 
> transform = T.Compose([ T.Resize(224), T.CenterCrop(224), T.ToTensor(), T.Normalize(mean=[0.5], std=[0.5]), ])
> 
> img = transform(img)[:3].unsqueeze(0)
> 
> with torch.no_grad(): features = dinov2_vits14(img, return_patches=True)[0]
> 
> print(features.shape) import matplotlib.pyplot as plt import numpy as np from sklearn.decomposition import PCA
> 
> pca = PCA(n_components=3) pca.fit(features)
> 
> pca_features = pca.transform(features) pca_features = (pca_features - pca_features.min()) / (pca_features.max() - pca_features.min()) pca_features = pca_features * 255
> 
> plt.imshow(pca_features.reshape(16, 16, 3).astype(np.uint8)) plt.savefig('meta_dog_features.png')
> 
> In dinov2/models/vision_transformer.py line 290 add
> 
> def forward(self, *args, is_training=False, return_patches=False, **kwargs): ret = self.forward_features(*args, **kwargs) if is_training: return ret elif return_patches: return ret["x_norm_patchtokens"] else: return self.head(ret["x_norm_clstoken"])
> 
> input: <img alt="meta_dog" width="248" src="https://user-images.githubusercontent.com/48384848/232604774-830adc36-6bf1-4fa3-8fbf-3d54e6376b28.png">
> 
> visualized features:
> 
> ![meta_dog_features](https://user-images.githubusercontent.com/48384848/232604731-ad7388e0-ce7a-4ef4-be49-6cb9e761e829.png)

how to visualize feature like this ?? , 
I tried as below 

```
import matplotlib.pyplot as plt
import numpy as np
from sklearn.decomposition import PCA


test_img = r"image.png"

features = extract_features_new(test_img)

pca = PCA(n_components=3)
pca.fit(features)

pca_features = pca.transform(features)
pca_features = (pca_features - pca_features.min()) / (pca_features.max() - pca_features.min())
pca_features = pca_features * 255

plt.imshow(pca_features.reshape(16, 16, 3).astype(np.uint8))


with this i'm getting error 
```
Output exceeds the size limit. Open the full output data in a text editor---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[133], line 11
      8 features = extract_features_new(test_img)
     10 pca = PCA(n_components=3)
---> 11 pca.fit(features)
     13 pca_features = pca.transform(features)
     14 pca_features = (pca_features - pca_features.min()) / (pca_features.max() - pca_features.min())
     
     
ValueError: Expected 2D array, got 1D array instead:
array=[ 0.48167408 -2.6765716  -1.8200531  ... -2.971799    1.1348227
 -1.9918671 ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.    
```

```

feature shape is 1024, how  would i fix this ?

**Comment by woctezuma** [comment]
> how to visualize feature like this ?? ,

- #23

**Comment by XiaominLi1997** [comment]
> @Suhail To generate features from the pretrained backbones, just use a transform similar to the standard one used for evaluating on image classification with the typical ImageNet normalization mean and std (see [what's used in the code](https://github.com/facebookresearch/dinov2/blob/main/dinov2/data/transforms.py#L78)). Also, as noted in the model card, the model can also use image sizes that are multiple of the patch size.

Hi, it seems that I can get feature embedding of [1, 256, 384] for an image, then I reshape it to [1, 16, 16, 384], I can get the visualized features. But, how can I get a feature map with a larger resolution because I wonna get finer info such as texture.

**Comment by purnasai** [comment]
Hi @XiaominLi1997, Use Larger models.
- feat_dim = 384 # vits14
- feat_dim = 768 # vitb14
- feat_dim = 1024 # vitl14
- feat_dim = 1536 # vitg14

So, you can use Vitg14 & Also Increase Input Image size in Multiple of 14. Ex: 518pix( i.e 14patchsize * 37pixels).
Hope this helps.

**Comment by ydove0324** [comment]
> ```python
> T.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
> ```

Why do you need to center to (0.485,0.456,0.406)? Is anywhere mentioning this?

**Comment by charchit-avataar** [comment]
@ydove0324 using the mean and standard deviation of imagenet is standard practice.

**Comment by charchit7** [comment]
@ydove0324 this is standard imagenet mean used for training. It's a common practice.

**Comment by darthvaddor** [comment]
> Yes, `get_intermediate_layers()` allows different approaches. This is similar to what is done in `linear.py` as mentioned above.
> 
> You could also use GeM pooled patch tokens with this output, as in `eval_copy_detection.py` for DINO (v1).

so I'm trying to see the intermediate layers of dinov2 given an image and I want to analyze their outputs. I want an embedding, and I'm trying to see if these intermediate outputs can be used instead.

so I ran this code:
```
dinov2 = torch.hub.load('facebookresearch/dinov2', 'dinov2_vits14_reg')
image_path = "/content/drive/MyDrive/image.jpg"

img = Image.open(image_path).convert('RGB')
img_tensor = image_transforms(img).unsqueeze(0).to(device)
img_tensor.shape

features = dinov2.forward_features(img_tensor)
```

error:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-47-d58d41f2b35d>](https://localhost:8080/#) in <cell line: 1>()
----> 1 features = dinov2.forward_features(img_tensor)

8 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py](https://localhost:8080/#) in _conv_forward(self, input, weight, bias)
    547                 self.groups,
    548             )
--> 549         return F.conv2d(
    550             input, weight, bias, self.stride, self.padding, self.dilation, self.groups
    551         )

RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

but my tensor shape is: torch.Size([1, 3, 224, 224])

and the get_intermediate_layers output is a tuple how do I interpret this. Also should I use the hub model or hugging face model for embeddings

**Comment by darthvaddor** [comment]
@woctezuma I'm trying to understand the embeddings generated by dinov2 torch and dinov2 in huggingface. huggingface outputs (b,257,768) where the cls embedding and patch embeddings are concatenated into a single 768 dimensional embedding?
Whereas the hub model outputs two seperate 768 dimensional embeddings for cls and patches. Is my understanding correct? Is there a difference in the output that these 2 generate. What's the best way to get an embedding for image retrieval

**Comment by tcourat** [comment]
Ideally, shouldn't you wrap the inference around 
`with torch.autocast('cuda', dtype=torch.float16)` as dinov2 was trained with mixed precision ?
