### ISSUE TITLE
Sparse Matching Demo example code?

### ISSUE THREAD

**Issue by Olimoyo** [facebookresearch/dinov2#208]
Hi,

Is there some example code for the sparse matching demo? 

Thanks!
Oliver

**Comment by patricklabatut** [comment]
Please follow the work-in-progress PR #187, I was planning to add code for sparse matching as well.

**Comment by Olimoyo** [comment]
Thank you!

**Comment by GZ-YourZY** [comment]
> 谢谢你！

Have you successfully modified the sparse matching code based on the PCA example code, and would like to exchange ideas?
