### ISSUE TITLE
help

### ISSUE THREAD

**Issue by qiantubu** [facebookresearch/dinov2#22]
Sorry, I installed -- extra index URL https://pypi.nvidia.com
CUML CU11 generated this error

pip install --extra-index-url https://pypi.nvidia.com cuml_cu11
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting cuml_cu11
  Using cached cuml_cu11-23.4.0.1681368248.tar.gz (6.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-install-lp6867xq\cuml-cu11_29831863f455450faf83190fcc7a7e3c\setup.py", line 137, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.

      This package can be installed as:
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com cuml_cu11
      ```
      ###########################################################################################

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

What is the problem?

**Comment by qiantubu** [comment]
> alreadly  deal .please  choose more lower versions.

**Comment by patricklabatut** [comment]
Closing as answered.
