### ISSUE TITLE
Input preprocessing for prediction

### ISSUE THREAD

**Issue by machur** [facebookresearch/dinov2#225]
Hi, I have a question regarding the preprocessing steps because I just can't wrap my head around it. I want to implement image preprocessing consistent with DINO2 pipeline, and I found the following steps in a couple of issues marked as documentation:

```
image_transforms = T.Compose([
    T.Resize(256, interpolation=T.InterpolationMode.BICUBIC),
    T.CenterCrop(224),
    T.ToTensor(),
    T.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
])
```

Here is the source code: https://github.com/facebookresearch/dinov2/blob/c3c2683a13cde94d4d99f523cf4170384b00c34c/dinov2/data/transforms.py#L78

What is the idea behind separate resize and center cropping? Why do we want remove the borders (along with some image information)? Is this related somehow to creating global/local views? It seems too narrow though and shouldn't matter during inference... Is it some assumption about the input data the models were trained on?

**Comment by MohammedSB** [comment]
I am pretty sure the resizing and center cropping is ImageNet related preprocessing.
It is not related to global/local views since those views are used for self-supervised pretraining, not fine-tuning/evaluation.

**Comment by machur** [comment]
So that's exactly why I'm asking since these don't look like meaningful steps in terms of image processing. I'm wondering why cannot we simply resize to 244 in one step - that's a usual way for other ImageNet-based models (like pretrained ResNet etc).

The only reason I figured out is as follows: pixel interpolation to "round" 256 sizes is faster, so first we resize, and then we crop to dimensions compatible with actual patch sizes (divisible by 14).

The reason I asked this question is that we have plenty of different models for embedding extraction in our pipelines and for now they all have identical preprocessing steps. This will be the first deviation, we will have to handle it, but I don't think it's actually different.

**Comment by machur** [comment]
@MohammedSB With ImageNet I've seen it rather with RandomCrop instead of CenterCrop, and it makes perfect sense - we want to cut out samples for the training from bigger images. But here I don't get the rationale behind the split into two separate steps, especially considering that they are static.

In my case, I have perfectly curated dataset of images which I could simply resize to 224, but DINO removes 16 pixels from the borders additionally in the preprocessing. My question is **why** do we get rid of parts of the input images. I prefer to fully understand the code I'm using.

**Comment by machur** [comment]
@MohammedSB thanks for pointing out the aspect-ratio issue. This makes sense, I thought the API of Transform.Resize returns an image of dimensions [size, size], but it actually returns [size * height / width, size] when called with only a single argument, so another transformation is needed to standardize the sizes.

Also, you may be right about the fact that interesting things are rather in the middle. Still, it looks like it's a property of ImageNet training set, not something that we need to follow with our own data.
