### ISSUE TITLE
Multi-GPU Usage for Depth Head with External Calls

### ISSUE THREAD

**Issue by chenshihfang** [facebookresearch/dinov2#228]
Hi, I appreciate the release of the Depth Head. I'd like to understand how to conduct training on multiple GPUs using the Depth Head through external calls.

For instance, in the following code snippet:

```python
def dinov2(model_name="dinov2_vitl14"):
    dinov2 = torch.hub.load('facebookresearch/dinov2', model_name)
    return dinov2
```

After wrapping the `dinov2` model with `DataParallel`, and providing multi-GPU data to it, I can get multi-GPU output like so:

```python
total_features = self.dinov2._get_intermediate_layers_not_chunked(images, [2,5,8,11])
```

However, when I wrap the depth model with `DataParallel`:

```python
def dinov2_Depth():
    # Omitted some necessary code same as depth_estimation.ipynb
    model = create_depther(cfg, backbone_model=backbone_model, backbone_size=backbone_name, head_type=HEAD_TYPE)
    load_checkpoint(model, head_checkpoint_url, map_location="cpu")
    model.cuda()
    return dinov2_Depth
```

And then provide multi-GPU data to it, it only returns data using a single GPU (cuda:0). For example:

```python
batch_fea =  dinov2_Depth.whole_inference(images, img_meta=None, rescale=True)
```

or

```python
batch_fea = self.dinov2_Depth.backbone(images)
batch_fea = self.dinov2_Depth.decode_head(batch_fea, img_metas=None)
```

Is there a correct way to get multi-GPU data returns with external calls? Thank you.

**Comment by VillardX** [comment]
> Hi, I appreciate the release of the Depth Head. I'd like to understand how to conduct training on multiple GPUs using the Depth Head through external calls.
> 
> For instance, in the following code snippet:
> 
> ```python
> def dinov2(model_name="dinov2_vitl14"):
>     dinov2 = torch.hub.load('facebookresearch/dinov2', model_name)
>     return dinov2
> ```
> 
> After wrapping the `dinov2` model with `DataParallel`, and providing multi-GPU data to it, I can get multi-GPU output like so:
> 
> ```python
> total_features = self.dinov2._get_intermediate_layers_not_chunked(images, [2,5,8,11])
> ```
> 
> However, when I wrap the depth model with `DataParallel`:
> 
> ```python
> def dinov2_Depth():
>     # Omitted some necessary code same as depth_estimation.ipynb
>     model = create_depther(cfg, backbone_model=backbone_model, backbone_size=backbone_name, head_type=HEAD_TYPE)
>     load_checkpoint(model, head_checkpoint_url, map_location="cpu")
>     model.cuda()
>     return dinov2_Depth
> ```
> 
> And then provide multi-GPU data to it, it only returns data using a single GPU (cuda:0). For example:
> 
> ```python
> batch_fea =  dinov2_Depth.whole_inference(images, img_meta=None, rescale=True)
> ```
> 
> or
> 
> ```python
> batch_fea = self.dinov2_Depth.backbone(images)
> batch_fea = self.dinov2_Depth.decode_head(batch_fea, img_metas=None)
> ```
> 
> Is there a correct way to get multi-GPU data returns with external calls? Thank you.

Hi， I am new to depth estimation. Since the autor released Depth Head and a inference demo with jupyter notebook and I can input my own image to get the depth map based one the released depth head, I still do not know how to TRAIN a depth head based on my own annotated depth data. Could you give me some instructions?  Thanks.
