### ISSUE TITLE
missing labels.txt

### ISSUE THREAD

**Issue by KochPJ** [facebookresearch/dinov2#233]
Hey Ho,

when i execute:

---------------------------------
from dinov2.data.datasets import ImageNet

for split in ImageNet.Split:
     dataset = ImageNet(split=split, root="MyPathRoot", extra="MYPathExtra")
     dataset.dump_extra()

---------------------------------
in order to generate the extra information used for Imagenet 1k i recieve the error:

    raise RuntimeError(f'can not read labels file "{labels_full_path}"') from e
RuntimeError: can not read labels file "<PATHTOIMAGENET>/labels.txt"

I downloaded ImageNet from the official website and i can use it just fine with Pytorch ImageNet dataset.
Where can i get the labels.txt file?

Best,
Paul

**Comment by patricklabatut** [comment]
It's surprisingly difficult to get a hand on this file in the wild... The expected file format should be "`<class id>`,`<class name>`" on each line, in the order of (numerical) ImageNet class indices. So first line would be "`n01440764`,`tench`" and last line would be "`n15075141`,`toilet tissue`". I will see if the data loader can be reworked to avoid such dependency.

Meanwhile, the closest file found online would be `LOC_synset_mapping.txt` from https://www.kaggle.com/competitions/imagenet-object-localization-challenge which after some light processing (only one label and add a comma separator) should match the expected format.

**Comment by patricklabatut** [comment]
Closing, tracked in #243

**Comment by JingruiYu** [comment]
Hi there,

I was under the impression that the code would be able to download and organize the ImageNet dataset in an empty folder specified by the root path. However, after running the code, I encountered the same error as above. Even after downloading the label.txt file to the root path, the error persisted. 
`FileNotFoundError: [Errno 2] No such file or directory: '/data/train'
I was wondering if there are any specific files that need to be present in the root folder for the code to work properly? Thanks!
