### ISSUE TITLE
Extracting teacher weights from the final checkpoint

### ISSUE THREAD

**Issue by vladchimescu** [facebookresearch/dinov2#235]
Hi,
I have trained DINOv2 / ViT-S on some custom data. Now I am trying to use the final model checkpoint (`model_final.rank_0.pth`) to extract teacher backbone weights:

```
pretrained_weights = 'checkpoints/model_final.rank_0.pth'
state_dict = torch.load(pretrained_weights, map_location="cpu")

# select the model key
state_dict = state_dict['model']
# only teacher backbone keys
state_dict = {key: value for key, value in state_dict.items() if 'teacher.backbone' in key}
# remove 'teacher.backbone.'
state_dict = {k.replace("teacher.backbone.", ""): v for k, v in state_dict.items()}

# load ViT-S
from dinov2.models import vits
model = vits.vit_small(patch_size=16)
# load state_dict into the model
model.load_state_dict(state_dict)
```

However, this fails due to the key mismatch:
```
RuntimeError: Error(s) in loading state_dict for DinoVisionTransformer:
	Missing key(s) in state_dict: "blocks.0.0.norm1.weight", "blocks.0.0.norm1.bias", "blocks.0.0.attn.qkv.weight", ...
Unexpected key(s) in state_dict: "blocks.1.norm1.weight", "blocks.1.norm1.bias", "blocks.1.attn.qkv.weight", ...
```
When going through the `state_dict` keys, I do find `'blocks.0.norm1.weight'` but not `'blocks.0.0.norm1.weight'` which `DinoVisionTransformer` expects. 

I am not sure what I am missing. Thank you in advance.

**Comment by qasfb** [comment]
It is easier to use the teacher_checkpoint.pth file inside the evaluation folder for your job; can you try it ?

**Comment by vladchimescu** [comment]
@qasfb Thank you for the fast reply. It doesn't work unfortunately and I still get the `_IncompatibleKeys` exception. I've tried the following:
```
pretrained_weights = 'eval/training_437499/teacher_checkpoint.pth'
state_dict = torch.load(pretrained_weights, map_location="cpu")
state_dict = state_dict['teacher']

# only the backbone keys
state_dict = {key: value for key, value in state_dict.items() if 'backbone' in key}
# remove 'teacher.backbone.'
state_dict = {k.replace("backbone.", ""): v for k, v in state_dict.items()}

model = vits.vit_small(patch_size=16)
# load state_dict into the model
model.load_state_dict(state_dict)
```
By the way, somehow the checkpoint of the very last iteration (440,800) wasn't saved even though the training ran through.

**Comment by qasfb** [comment]
Can you init your model with your config using this function ?
https://github.com/facebookresearch/dinov2/blob/main/dinov2/models/__init__.py#L39

Essentially there is a "block_chunks" parameter involved there that needs to be passed to the model if you load it.
Otherwise you can work on the names in the state_dict; they have the form:
blocks.blockchunkidx.layeridx.***

**Comment by vladchimescu** [comment]
@qasfb Thanks. I added the `block_chunks=0` argument and now I only have some unexpected keys in the `state_dict`:

```
RuntimeError: Error(s) in loading state_dict for DinoVisionTransformer:
Unexpected key(s) in state_dict: "blocks.0.ls1.gamma", "blocks.0.ls2.gamma", "blocks.1.ls1.gamma", ...
```

They are all of type `ls1.gamma` and `ls2.gamma`. Am I missing an argument to the model?

**Comment by qasfb** [comment]
yes, you can put init_values=1, that activates the layerscale layers

**Comment by Arkkienkeli** [comment]
You can also simply rerun your training command (if you use `dinov2/train/train.py`) with `--eval_only` flag. That will create a `teacher_checkpoint.pth` from a very last iteration of your training in case it wasn't saved in training time.

**Comment by DinghaoZheng** [comment]
Hi,
I met the same question as you, but the bug still exists after I used the same code mentioned above. Could you share the whole code? thank you 

Below is my code:
import torch
import torch.nn as nn
from dinov2.models import vision_transformer as vits

pretrained_weights = 'dinov2/output/eval/training_112499/teacher_checkpoint.pth'
state_dict = torch.load(pretrained_weights, map_location="cpu")
state_dict = state_dict['teacher']

# only the backbone keys
state_dict = {key: value for key, value in state_dict.items() if 'backbone' in key}
# remove 'backbone.' prefix
state_dict = {k.replace("backbone.", ""): v for k, v in state_dict.items()}

model = vits.vit_base(patch_size=14, block_chunks=0, init_values=1)
# load state_dict into the model
model.load_state_dict(state_dict)
