### ISSUE TITLE
Use Dinov2 as a defect detection system

### ISSUE THREAD

**Issue by shrinand1996** [facebookresearch/dinov2#236]
I would like to test how dinov2 performs on defect detection tasks. I can train the classifier if i have both good and bad images. But, i want to train on only good images and let the dinov2 calculate embedding and find bad images automatically. 
Any ideas how that can be achieved?

I was thinking of maybe finding the cosine similarity of the good images with the test image but that would require a lot of computation...

**Comment by qasfb** [comment]
I believe this is a difficult problem if you don't have negatives in your classification setup.
