### ISSUE TITLE
Will the LVD-142M dataset or data processing codes be released?

### ISSUE THREAD

**Issue by XiaohuJoshua** [facebookresearch/dinov2#24]
Thanks for the outstanding work. Do you have the plan to release the LVD-142M dataset or codes for data processing?

**Comment by ccharest93** [comment]
Probably will not be released, image dataset this large are usually not release since it could open them up to copyright suits, similar thing with JFT-300M dataset from Google.

**Comment by patricklabatut** [comment]
Releasing LVD-142M is not something that we are considering releasing, I am afraid. Re: open-sourcing the data curation code, this could depend on feedback and interest from the community.

**Comment by salonit77** [comment]
Would it be possible to share additional details regarding the deduplication part used in the data curation pipeline. Or how that can be replicated for a custom dataset.

**Comment by XiaohuJoshua** [comment]
> Would it be possible to share additional details regarding the deduplication part used in the data curation pipeline. Or how that can be done for a custom dataset.

+1.

**Comment by woctezuma** [comment]
> Would it be possible to share additional details regarding the deduplication part used in the data curation pipeline. Or how that can be done for a custom dataset.

It is probably something simple like [`idealo/imagededup`](https://github.com/idealo/imagededup).

In Figure 3, you can see that there is an image which is identical to one of the curated dataset, and another image which has a different ratio but is otherwise identical to another one of the uncurated dataset.

![Dedpulication](https://i.imgur.com/VnH1VTh.png)

**Comment by XiaohuJoshua** [comment]
Thanks for your reply.

**Comment by salonit77** [comment]
@woctezuma  Thank you for the reply.. I was able to follow the A3 section and get some deduplication results

**Comment by FrancescoSaverioZuppichini** [comment]
@salonit77 hi :) could you share the code?

**Comment by yyyyyyfs** [comment]
> depend

Thanks for your reply! I have a question about the deduplication method SSCD mentioned in your paper. I would like to confirm that SSCD is only used to extract embedding？ Then use the Faiss library to calculate the similarity between embeddings？

**Comment by yyyyyyfs** [comment]
> > Would it be possible to share additional details regarding the deduplication part used in the data curation pipeline. Or how that can be done for a custom dataset.
> 
> It is probably something simple like [`idealo/imagededup`](https://github.com/idealo/imagededup). **Edit:** the procedure is applied to embeddings as shown on Figure 3 rather than images, so it is a bit more complex.
> 
> In Figure 3, you can see that duplicates include:
> 
> * an image which is identical to one of the curated dataset,
> * another image which has a different ratio but is otherwise nearly identical to another one of the uncurated dataset.
> 
> ![Dedpulication](https://camo.githubusercontent.com/a7d99d90a88b9321689219717982c6e5b1f7c3b51e5242ca12078c1f9f913bae/68747470733a2f2f692e696d6775722e636f6d2f566e48315654682e706e67)
> 
> **Edit:** You can find more information in the paper. It is a bit more complex as it is done on the embeddings. However, I believe a method using image hashes is also used in a first deduplication process, as "PCA hash" is mentioned. 🤔
> 
> ![Paper](https://camo.githubusercontent.com/fb27943ac4fbb2d302a51bd5207ab50f48c72e2ac05ab82dd10bb5c15748ef52/68747470733a2f2f692e696d6775722e636f6d2f764277675545552e706e67)
> 
> ![Appendix](https://camo.githubusercontent.com/57772d56c059d38a21b12285df50529eaf84a4b86e8984caaf82acae49b1fe9b/68747470733a2f2f692e696d6775722e636f6d2f373578633969702e706e67)

Thanks for your reply~ 
About  implementation details，I still have some questions。If I have 5B images，but I only have few gpus，how can I do this work？ Reading a large amount of data into memory simultaneously is also a serious problem. Do you have any good suggestions?

**Comment by forever208** [comment]
> Releasing LVD-142M is not something that we are considering releasing, I am afraid. Re: open-sourcing the data curation code, this could depend on feedback and interest from the community.

So, the editor said something non-existing in openreview :D
https://openreview.net/forum?id=a68SUt6zFt

**Comment by dvikdvik** [comment]
soo,, release it!! 🥇

**Comment by rfan-debug** [comment]
> > > Would it be possible to share additional details regarding the deduplication part used in the data curation pipeline. Or how that can be done for a custom dataset.
> > 
> > 
> > It is probably something simple like [`idealo/imagededup`](https://github.com/idealo/imagededup). **Edit:** the procedure is applied to embeddings as shown on Figure 3 rather than images, so it is a bit more complex.
> > In Figure 3, you can see that duplicates include:
> > 
> > * an image which is identical to one of the curated dataset,
> > * another image which has a different ratio but is otherwise nearly identical to another one of the uncurated dataset.
> > 
> > ![Dedpulication](https://camo.githubusercontent.com/a7d99d90a88b9321689219717982c6e5b1f7c3b51e5242ca12078c1f9f913bae/68747470733a2f2f692e696d6775722e636f6d2f566e48315654682e706e67)
> > **Edit:** You can find more information in the paper. It is a bit more complex as it is done on the embeddings. However, I believe a method using image hashes is also used in a first deduplication process, as "PCA hash" is mentioned. 🤔
> > ![Paper](https://camo.githubusercontent.com/fb27943ac4fbb2d302a51bd5207ab50f48c72e2ac05ab82dd10bb5c15748ef52/68747470733a2f2f692e696d6775722e636f6d2f764277675545552e706e67)
> > ![Appendix](https://camo.githubusercontent.com/57772d56c059d38a21b12285df50529eaf84a4b86e8984caaf82acae49b1fe9b/68747470733a2f2f692e696d6775722e636f6d2f373578633969702e706e67)
> 
> Thanks for your reply~ About implementation details，I still have some questions。If I have 5B images，but I only have few gpus，how can I do this work？ Reading a large amount of data into memory simultaneously is also a serious problem. Do you have any good suggestions?

@yyyyyyfs (Not the author..just want to put my two cents:) Processing 5B images with a few gpus would take years. Personally I'd store images on GCS buckets and try to apply for their free TPU units to process it. My personal experience is that a cloud provider like GCP usually optimize the connection between storage and computing units very well so you don't have to worry about speed of loading images into memory. You may just treat it like an embarrassingly data parallel process.

**Comment by usryokousha** [comment]
If you look at the date of the paper and the available large datasets at the time the LAION-400M dataset seems like a good uncurated dataset to target.  Furthermore, using the hidden features from a CLIP model would be great to compare with images in the curated dataset.  The embedding model and the uncurated dataset were unspecified but I feel like these are good guesses.

The rest of the processing was clearly explained in the paper and could be deplicated.  @rfan-debug  mentioned that the processing of the data could be compute intense but I think the major limitation would be storage.  Remember you would need to make available all the curated datasets AND the uncurated dataset.
