### ISSUE TITLE
Non-determinism in getting last layer patch tokens.

### ISSUE THREAD

**Issue by MohammedSB** [facebookresearch/dinov2#249]
Hi,
When I do something like:
```Python
feature_model_with_inter = ModelWithIntermediateLayers(model, n_last_blocks=1, autocast_ctx=autocast_ctx)

embeddings_one = feature_model_with_inter(image)[0][0] # First indexing into layer, then into patch tokens.
with autocast_ctx():
    embeddings_two = model.forward_features(x)['x_norm_patchtokens']
print(torch.equal(embeddings_one, embeddings_two))
```
I get `False`.
As I understand it, the `ModelWithIntermediateLayers` class is used for getting features of the last n blocks, so the code above should give me the features of the last block. Both using the same auto-casting, and both use `LayerNorm`.

When I compare the two features, they are similar but not exactly the same, not sure why.

**Comment by qasfb** [comment]
First, is the model running in .eval() mode ?
There is also a bit of randomness in neural network operations in general. Matrix multiplications are not exactly deterministic, and the error accumulates during the sequence of operations.

**Comment by MohammedSB** [comment]
The model is in eval mode.
