### ISSUE TITLE
DINOv2 ViT Registers

### ISSUE THREAD

**Issue by dillonalaird** [facebookresearch/dinov2#251]
Will the implementation for ViT Registers for DINOv2 be added to this repo? This is from the "Vision Transformers Need Registers" [paper](https://arxiv.org/abs/2309.16588), I was assuming it would be added here because the authors are from Fair

**Comment by patricklabatut** [comment]
Yes, once ready, the models and code adjustments will appear in this repository. Stay tuned.

**Comment by patricklabatut** [comment]
Available with the just merged PR #282.
