### ISSUE TITLE
An error in the blog post about the project presentation

### ISSUE THREAD

**Issue by jixiedy** [facebookresearch/dinov2#256]
I found an error in the blog post (https://ai.meta.com/blog/dino-v2-computer-vision-self-supervised-learning/):

In the section "Releasing a family of high-performance pretrained models," the last sentences of the third-to-last paragraph appear again in the second-to-last paragraph. I would appreciate it if the authors could verify and correct this.

**Comment by patricklabatut** [comment]
Thanks for your feedback, we will relay it to the editorial team for the blog.
