### ISSUE TITLE
MMCV: 'EncoderDecoderMask2Former is not in the models registry'

### ISSUE THREAD

**Issue by julkaztwittera** [facebookresearch/dinov2#258]
I tried to run MaskFormer with Dinov2. Everything worked well in your Colab, but when I tried to use it on my machine, I got the following error:

```
KeyError: 'EncoderDecoderMask2Former is not in the models registry'
```

I have mmcv-full==1.5.0 and mmsegmentation==0.27.0, just like in the extras.

**Comment by julkaztwittera** [comment]
OK, just forgot to import `dinov2.eval.segmentation_m2f.models.segmentors`.

**Comment by GZ-YourZY** [comment]
请问您是如何安装的mmcv-full==1.5.0 and mmsegmentation==0.27.0,可否提供一下指导

**Comment by luckmouse** [comment]
Could you tell me how to install mmcv-full==1.5.0 and mmsegmentation==0.27.0?
