### ISSUE TITLE
High-Resolution Adaptation

### ISSUE THREAD

**Issue by MarahHalawa** [facebookresearch/dinov2#291]
Hi,

As also mentioned in this [issue](https://github.com/facebookresearch/dinov2/issues/211) we are not able to find the part of the code that adapt the resolution in the end of the pertaining to 518X518 as mentioned in the paper. Does this part not included in the repo or is there any hyperparameter in the config can control the image’s resolution?

Thanks!

**Comment by patricklabatut** [comment]
Closing this issue to use #211 to track.
