### ISSUE TITLE
short trained ViT-L/16 model, PCA visualization background foreground reverse problem

### ISSUE THREAD

**Issue by justzhanghong** [facebookresearch/dinov2#292]
I use the visualzation tools: https://github.com/MartinBurian/dinov2/blob/experiments/experiments/fg_segmantation.ipynb,  visulize the features.
(1) official ViT-L/14 model, the result is as I expected.
![Snipaste_2023-11-01_11-19-25](https://github.com/facebookresearch/dinov2/assets/39931535/cfd1799d-4764-4ac1-852e-86e461028f0b)

(2) i use "Fast setup: training DINOv2 ViT-L/16 on ImageNet-1k" config retrained ViT-L/16 model, the result is opposite to expected..
![Snipaste_2023-11-01_11-22-48](https://github.com/facebookresearch/dinov2/assets/39931535/95f4c803-797f-40b3-bd4f-d47fcbceed48)

Is the number of iterations too few? Or is there too little training data? Does anyone have a similar phenomenon? Does anyone know why?

**Comment by justzhanghong** [comment]
I found the pattern. Saving some models during the training process is as expected, but the final model is contrary to expectations.
![image](https://github.com/facebookresearch/dinov2/assets/39931535/6bc6f5b9-c7ce-4af3-b9e0-7c97919f285a)
![image](https://github.com/facebookresearch/dinov2/assets/39931535/b8c08b73-888f-48a3-9643-551369db9fe6)

The number is iteration.

**Comment by qasfb** [comment]
i think thresholding with the PCA can be done either by zeroing all values above some threshold, or all values below some threshold, maybe try both and check if you get something
