### ISSUE TITLE
RuntimeError: Cannot find callable dinov2_vitl14_reg in hubconf

### ISSUE THREAD

**Issue by tnarek** [facebookresearch/dinov2#296]
Hello,

Thanks for releasing the weights for the models with Registers! Very cool work.
I am encountering an issue when trying to load them via:

`dinov2_vitl14_reg = torch.hub.load('facebookresearch/dinov2', 'dinov2_vitl14_reg')`.

I'm getting the following error message: `RuntimeError: Cannot find callable dinov2_vitl14_reg in hubconf`.

Could you please help in resolving it?. I've tried upgrading from pytorch 2.0.0 to 2.1.0+cu118, but still getting the same error.

Thanks.

**Comment by qasfb** [comment]
I think it could be a cache issue, can you try with torch.hub.load(..., force_reload=True) ?

**Comment by tnarek** [comment]
Awesome, it works! thanks @qasfb!
I'm closing the issue.
