### ISSUE TITLE
Performance degradation for multi node training

### ISSUE THREAD

**Issue by GravityZL** [facebookresearch/dinov2#303]
Hi, I have a cluster without slurm(Azureml cluster, Tesla V100). And I compared the training on single gpu, multi gpus on one node, and multi nodes. The results show that when it is trained on multi nodes, there is a significant performance degradation:

it takes 1 day to finish on one gpu and multi gpus within one node, but it takes roughly 3 days to finish the training with 2 nodes, and with four nodes, it takes even longer.

Do you have some idea what happened here? It is much appreciated if you can help.

Thank you!

**Comment by usuyama** [comment]
Are you using InfiniBand-connected nodes on AzureML?

**Comment by GravityZL** [comment]
> Are you using InfiniBand-connected nodes on AzureML?

yes, not this issue has been fixed, it can run on multi nodes with no performance degradation.

**Comment by GravityZL** [comment]
Issue solved

**Comment by usuyama** [comment]
What was the issue and how did you solve?

**Comment by TumVink** [comment]
@GravityZL Heyy could you share how did you solve the issue? And if you donot mind, I think your script of training DINO on multi nodes without SLURM is also valueable.

Thanks!
