### ISSUE TITLE
Are registers good for small models like ViT-S?

### ISSUE THREAD

**Issue by JUGGHM** [facebookresearch/dinov2#308]
Thank you for the impressive DINO v2 models. We are now using them as our image backbones. 

When I am choosing a small backbone from DINO v2, I wonder which should be better: dinov2-s or dinov2-s-reg?
I find that in your report there is no significant difference between these two models?

**Comment by qasfb** [comment]
I think they are quite similar, except the reg model has less artifacts in the feature maps.
Depending on your use-case there might be an effect on your downstream performance.

**Comment by JUGGHM** [comment]
> I think they are quite similar, except the reg model has less artifacts in the feature maps. Depending on your use-case there might be an effect on your downstream performance.

Thank you for your suggestions!
