### ISSUE TITLE
Config for training ViT-g /14?

### ISSUE THREAD

**Issue by GravityZL** [facebookresearch/dinov2#311]
Hi, I have question regarding the training of ViT-g /14 model, in the paper, it is stated that the batch size is 3072. And in the vitg14.yaml, the batch_size_per_gpu is set to be 12, so I guess the number of gpus is 256? And since you trained ViT-g /14 on a dataset of 142M images, how do you define the iteration length? is it still 1250? And how about the epochs, still 500?

Thank you!

**Comment by qasfb** [comment]
You are right: 256 gpus, and epoch length 1250, for 500 epochs.
