### ISSUE TITLE
 Modifying Dataset Configuration for Self-Distillation with Custom Dataset

### ISSUE THREAD

**Issue by MarioAvolio** [facebookresearch/dinov2#312]
I'm looking to implement self-distillation using the `train.py` script from [this file](https://github.com/facebookresearch/dinov2/blob/main/dinov2/train/train.py). However, I need to customize it to work with my own dataset.

The dataset configuration file can be found [here](https://github.com/facebookresearch/dinov2/blob/main/dinov2/data/datasets/image_net_22k.py). Could someone provide guidance on how to modify this configuration file for my specific dataset?

**Comment by ayushnangia** [comment]
did you figure out how to just pretrain by initializing the weights from the model weights given? @MarioAvolio
