### ISSUE TITLE
Positional Embedding of pretrained backbone ViTL/14 is 1370x1024, instead of 257x1024 as expected

### ISSUE THREAD

**Issue by davidanglada** [facebookresearch/dinov2#316]
Hello to everyone, 

I'm trying to retrain the DinoV2 ViTL/14 starting from the [already pretrained backbone ViTL/14](https://dl.fbaipublicfiles.com/dinov2/dinov2_vitl14/dinov2_vitl14_pretrain.pth) but I'm facing the following error:

```
RuntimeError: Error(s) in loading state_dict for DinoVisionTransformer:
        size mismatch for pos_embed: copying a param with shape torch.Size([1, 1370, 1024]) from checkpoint, the shape in current model is torch.Size([1, 257, 1024]).
```

The way that I'm loading the weights is the following, edited in the `ssl_meta_arch.py` file:

```
if cfg.student.pretrained_weights:
            state_dict = torch.load(cfg.student.pretrained_weights)
            logger.info(f"OPTIONS -- pretrained weights: loading from {cfg.student.pretrained_weights}")
            student_backbone.load_state_dict(state_dict, strict=False)
```

Where is the problem here? Does that mean that the pretrained backbone uses patches of size 6, which would mean that the patch grid is 37x37, ending with 1369 patch tokens? 

How can I reuse the pretrained backbone in training?

Thank you very much!

David

**Comment by evyatar-bur** [comment]
If I'm not mistaken this happens because the pre-trained backbone is trained with img_size=518, while you are probably using the default value which is img_size=224.

Try changing to img_size=518, and preprocessing your images accordingly to be 3X518X518, I believe this should solve your problem.

**Comment by zshn25** [comment]
@evyatar-bur, is there a way to make the model (trained with 518), work with other image sizes?

From what I understand, there is [this function](https://github.com/facebookresearch/dinov2/blob/e1277af2ba9496fbadf7aec6eba56e8d882d1e35/dinov2/models/vision_transformer.py#L179) which adapts the pos_embed to other image sizes (that are multiples of patch size)

**Comment by Antoine-Audras** [comment]
unless you interpolate the embedding matrix to fit your token size (which might have effects on performances), the only way is to resize your image to fit the pretraining size.
