### ISSUE TITLE
Difference between DINO and DINOv2

### ISSUE THREAD

**Issue by Tulsishah** [facebookresearch/dinov2#318]
1. What's the difference b/w DINO and DINOv2?
2. What's the plan of using torch.compile feature in DINOv2 if not already there?

**Comment by qasfb** [comment]
So the difference between DINO and DINOv2 is:
- the procedure introduced in the iBOT paper
- the differences noted in the ablation study in the DINOv2 paper
- the scale of models and data

About torch.compile, we are considering it and we are working on handling, within pytorch, some optimized operators that are currently only present in the xformers library.

**Comment by Tulsishah** [comment]
Any ETA on supporting torch.compile ?

**Comment by qasfb** [comment]
At least after Pytorch 2.2 is released I would say.
