### ISSUE TITLE
Question: Depth information 

### ISSUE THREAD

**Issue by amughrabi** [facebookresearch/dinov2#325]
Does the depth information we extract from DinoV2 correspond to real measures (i.e., exact real-world distance), or is it accurate up to a scaling factor? 

Thanks a million,
Ahmad

**Comment by qasfb** [comment]
I'm not sure, I recommend you check, for the nyu-depth model, what the dataset provides as ground truth and walk back from there: https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html

**Comment by amughrabi** [comment]
Looks interesting; thanks for sharing! I will have a look and keep this issue posted.

**Comment by qasfb** [comment]
Please reopen if there are updates
