### ISSUE TITLE
Using default transforms when creating embeddings index - confusion on resize and crop transform

### ISSUE THREAD

**Issue by lehigh123** [facebookresearch/dinov2#326]
I am using DinoV2 with FAISS to do similarity search across a database of images. See these DinoV2-related [issues](https://github.com/facebookresearch/dinov2/issues/53) on this. 

In this [thread](https://github.com/facebookresearch/dinov2/issues/2) @patricklabatut mentions 

> @Suhail To generate features from the pre-trained backbones, just use a transform similar to the standard one used for evaluating on image classification with the typical ImageNet normalization mean and std (see [what's used in the code](https://github.com/facebookresearch/dinov2/blob/main/dinov2/data/transforms.py#L78)). Also, as noted in the model card, the model can also use image sizes that are multiple of the patch size.

The transforms that are linked in the corresponding code have a resize of 256 followed by a center crop of 224 - does this mean that given an image that is 256x256 32 pixels are ignored horizontally and vertically (because the center crop is **less** than the resize)?

If the images in my dataset have distinctive imagery on their borders does this mean these default transforms will crop that information out?

**Comment by qasfb** [comment]
Yes this is what it means, you can try without cropping. Maybe check what gives you the best results for your case ?

**Comment by lehigh123** [comment]
Thanks! removing the cropping gave better results for my use case (library of book cover images)
