### ISSUE TITLE
Should embeddings be normalized when adding them to a search index?

### ISSUE THREAD

**Issue by lehigh123** [facebookresearch/dinov2#327]
When using DinoV2 to do image similarity search should the embeddings be normalized before adding them to the index? This is a common pattern when using CLIP for similarity search (example [from CLIP readme](https://github.com/openai/CLIP))and I am wondering if DinoV2 is the same way.

**Comment by qasfb** [comment]
Please reopen if there are updates

**Comment by TutubanaS** [comment]
Normalize your vectors when using cosine distance. No need to normalize when using L2. However, cosine seems to be outperforming L2, so using cosine with normalized vectors is the best bet for similarity search purposes.
