### ISSUE TITLE
RuntimeError: Cannot find callable dinov2_vits14_reg in hubconf

### ISSUE THREAD

**Issue by Zhangdylan83** [facebookresearch/dinov2#329]
I am able to load the ones without register. However, I couldn't load the one with register using torch.hub.load('facebookresearch/dinov2', 'dinov2_vits14_reg') and it always shows RuntimeError: Cannot find callable dinov2_vits14_reg in hubconf.  Really eager to know the reason.    
The reason why I want to switch from vits14 to vits14_register is because under vits14, black background is brighter than the digit (target is darker), which is the opposite of what I expected. It may be encoding something in the black areas. 
<img width="816" alt="Screenshot 2023-11-28 at 6 00 23 PM" src="https://github.com/facebookresearch/dinov2/assets/66267672/eff831e8-25d0-4635-b8c4-3eae0071648b">

<img width="880" alt="Screenshot 2023-11-28 at 6 00 09 PM" src="https://github.com/facebookresearch/dinov2/assets/66267672/2e61796c-c562-477c-ae4d-cfffe17126da">

**Comment by patricklabatut** [comment]
See #296 and #309: don't forget to specify `force_reload=True` in the call to `torch.hub.load()` (if you have previously used DINOv2 backbones w/o registers), otherwise your code will hit the outdated PyTorch Hub local cache.
