### ISSUE TITLE
High resolution image result with NaN features

### ISSUE THREAD

**Issue by TurtleSmoke** [facebookresearch/dinov2#33]
Hello,

I'm having an issue with Dinov2 while trying to use it with high-resolution images like the one available at [this link](https://unsplash.com/photos/Nyvq2juw4_o). The problem is that the features returned by the model contain NaN values. This issue occurs with all four available models and is consistently present for images around the same size.

I would like to know if you have any ideas about what could be causing this problem. Here's an minimal example:

```python
import torch
import numpy as np
import torchvision.transforms as T
from PIL import Image
import hubconf

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dino = hubconf.dinov2_vits14().to(device)  # Same issue with larger model
img = Image.open('4k.png')
pw, ph = np.array(img.size) // 14

transform = T.Compose([
    T.Resize((14 * ph, 14 * pw), interpolation=T.InterpolationMode.BICUBIC),
    T.ToTensor(),
    T.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
])

tensor = transform(img)[:3].unsqueeze(0).to(device)
with torch.no_grad():
    features = dino.forward_features(tensor)['x_norm_patchtokens'][0]

print(features)  # NaN
```

**Comment by ccharest93** [comment]
You could make a debug function that checks the current values of the embedding vector for NaN entries, then insert that function btw various layers of the model to see in which layer the NaN start to appear, it might help us help you.

**Comment by TurtleSmoke** [comment]
After debugging the issue further, I found that the problematic function causing NaN values in the features is [memory_efficient_attention](https://github.com/facebookresearch/dinov2/blob/f8969297dbe53373b4041bf47d997a8dcc8d2077/dinov2/layers/attention.py#L80), which is part of the [xFormers](https://github.com/facebookresearch/xformers)  library used by Dinov2. Here is the relevant code snippet from Dinov2's [attention.py](https://github.com/facebookresearch/dinov2/blob/f8969297dbe53373b4041bf47d997a8dcc8d2077/dinov2/layers/attention.py) file:

https://github.com/facebookresearch/dinov2/blob/f8969297dbe53373b4041bf47d997a8dcc8d2077/dinov2/layers/attention.py#L65-L85

The output tensor is full of NaN during the forward pass of the first block.

**Comment by ccharest93** [comment]
https://github.com/facebookresearch/dinov2/issues/19#issuecomment-1514310057

Shows how to replace memory_efficient_attention with normal attention, could fix your issue.

**Comment by TurtleSmoke** [comment]
Regrettably, I need this function for the purpose of saving memory since the image necessitates nearly 100 gigabytes of RAM, which surpasses my requirements.

**Comment by TurtleSmoke** [comment]
I was somehow able to find an image that work without `memory_efficient_attention` but not with. I think `xFormers` might be struggling to handle attention when there are just too many patches to deal with. It's a bit confusing, to be honest.

**Comment by TurtleSmoke** [comment]
It seems that I did not make enough research before creating this issue:  [[0.0.18] memory_efficient_attention NaNs when seqlen>32768 #719](https://github.com/facebookresearch/xformers/issues/719)

I'll try upgrading and determine if this will resolve the problem.

**Comment by TurtleSmoke** [comment]
This resolved the problem, it works with the version `xformers==0.0.19.dev516`
