### ISSUE TITLE
Starting self-supervised training with registers

### ISSUE THREAD

**Issue by kusstox** [facebookresearch/dinov2#337]
Is there an implementation to start a self-supervised training with registers, e.g. for the ImageNet training which is reported in the readme: [https://github.com/facebookresearch/dinov2?tab=readme-ov-file#fast-setup-training-dinov2-vit-l16-on-imagenet-1k](https://github.com/facebookresearch/dinov2?tab=readme-ov-file#fast-setup-training-dinov2-vit-l16-on-imagenet-1k)

**Comment by qasfb** [comment]
Hi !
Yes you can set student.num_register_tokens to 4 in your config, it is 0 by default: https://github.com/facebookresearch/dinov2/blob/main/dinov2/configs/ssl_default_config.yaml#L83
