### ISSUE TITLE
Further dinov2 ssl training

### ISSUE THREAD

**Issue by hussein-jafarinia** [facebookresearch/dinov2#339]
Hi.
Thanks for sharing the great job.
Is there any recipe for further training in dinov2 ssl style of the pretrained weights on custom datasets based on available weights which are probably on student or teacher? (for example if I want to further ssl train in dinov2 ssl style to medical domain what should be my student and what should be my teacher? should they be the same or one of them be random initialization?)

**Comment by qasfb** [comment]
Hi ! Resuming training using existing weights is not something that we support at this point !

**Comment by TimDarcet** [comment]
Hi!
We don't have any official recommendation, nor is there a feature for that in the code. However, it should be very doable to modify the code so that it loads pretrained weights to initialize the student and teacher, and re-train on your dataset. The heads will be randomly initialized at first, which may or may not be an issue (we have no experience on that). You will need to implement your dataloading and possibly tweak the schedules.

**Comment by hussein-jafarinia** [comment]
Your weights only include backbone (which is either teacher or student). So I don't see any way for doing what you say. Am I missing something?

**Comment by TimDarcet** [comment]
The weights we release are only teacher, but teacher and student are quite close at the end of training anyway. I think you can initialize both networks with the official weights and it should not cause trouble

**Comment by ayushnangia** [comment]
did you figure out how to just pretrain by initializing the weights from the model weights given? @hussein-jafarinia

**Comment by ys566473** [comment]
I have also tried to load the weights and got a size mismatch in the 'pos_embed' layer.
the weights of vitl14 have 'pos_embed' layer size of [1,1370,1024], indicating images of size 592x592 and patch size 16. how does that coincide with the ssl config parameter of global_crops_size=224?

**Comment by MyHogsmeade** [comment]
The problem I encountered is that when the training model configuration is set to 'student.ffn_layer: swiglufused', the parameters of the official model (e.g., vitl14_pretrain.pth) cannot be matched. How should I load the official model and continue training?

**Comment by 1921134176** [comment]
> 我遇到的问题是，当训练模型配置设置为'student.ffn_layer: swiglufused'时，无法匹配官方模型（例如vitl14_pretrain.pth）的参数，请问应该如何加载官方模型继续训练呢？

Except for vit-g, all other official models use mlp for their ffn layers. In addition, the official open source weights and pre trained model weights have different keys, mainly reflected in the prefix, which needs to be converted.
