### ISSUE TITLE
Train vit-L16 in ImageNet-1k, got confusing files.

### ISSUE THREAD

**Issue by JoJoistheBestOne** [facebookresearch/dinov2#34]
https://github.com/facebookresearch/dinov2/blob/main/dinov2/data/datasets/image_net.py#L103-L110

what does those file come from?
f"entries-{split.value.upper()}.npy"
f"class-ids-{split.value.upper()}.npy"
f"class-names-{split.value.upper()}.npy"

**Comment by JoJoistheBestOne** [comment]
any updates?🍑

**Comment by yukeyiniupi** [comment]
> 任何更新？🍑

![image](https://user-images.githubusercontent.com/54205068/233886649-0e6cf7c7-0739-411e-8107-e8f701a37103.png)

You can use this function to generate those files.

**Comment by patricklabatut** [comment]
Will submit and merge a PR (likely today or tomorrow) that documents the required metadata and simplifies this (auto-generates it).

**Comment by ferreirafabio** [comment]
Thank you. Better late than never, I guess

**Comment by patricklabatut** [comment]
@ferreirafabio @JoJoistheBestOne @yukeyiniupi Just merged some documentation and code improvements to facilitate following the instructions to run evaluation and training on ImageNet-1k, hope this helps.
