### ISSUE TITLE
ModuleNotFoundError: No module named 'dinov2.hub'

### ISSUE THREAD

**Issue by logogriph2** [facebookresearch/dinov2#340]
Trying:
dinov2_vits14 = torch.hub.load('facebookresearch/dinov2', 'dinov2_vits14')
  
get error:

File "/home/admin2/.local/lib/python3.9/site-packages/torch/hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/admin2/.local/lib/python3.9/site-packages/torch/hub.py", line 584, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "/home/admin2/.local/lib/python3.9/site-packages/torch/hub.py", line 98, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/admin2/.cache/torch/hub/facebookresearch_dinov2_main/hubconf.py", line 7, in <module>
    from dinov2.hub.backbones import dinov2_vitb14, dinov2_vitg14, dinov2_vitl14, dinov2_vits14
ModuleNotFoundError: No module named 'dinov2.hub'

**Comment by logogriph2** [comment]
fixed by reinstalling from a source

**Comment by Hao-Ping** [comment]
@logogriph2 Hello, May I ask which part and how do you reinstall to fix the problem? Thank you

**Comment by Revist** [comment]
In my case I had another repo installed that had package dinov2 inside it. i.e. another_repo/dinov2 was added to sys.path. Then hub was not inside this and this repo was of more importance than local dino repo downloaded by torch.hub and added to sys.path. removing this package solved the problem.

**Comment by SohamTolwala** [comment]
got to import the vits model by running - "from dinov2.dinov2.hub.backbones import dinov2_vits14, dinov2_vitb14, dinov2_vitg14, dinov2_vitl14, dinov2_vits14"

BUT, still getting the same issue while loading the pretrained model i.e. "ModuleNotFoundError: No module named 'dinov2.hub'"


anyone facing the same??

**Comment by baldassarreFe** [comment]
If you're loading the models using torch hub, can you force a re-download of the repository? Use `force_reload=True` or delete  the folder `~/.cache/torch/hub/facebookresearch_dinov2_main`

https://docs.pytorch.org/docs/stable/hub.html#:~:text=pytorch/vision%3A0.10%E2%80%99-,force_reload%20(bool%2C%20optional)%20%E2%80%93%20whether%20to%20discard%20the%20existing%20cache%20and%20force%20a%20fresh%20download.%20Default%20is%20False.,-skip_validation%20(bool

**Comment by SohamTolwala** [comment]
> If you're loading the models using torch hub, can you force a re-download of the repository? Use `force_reload=True` or delete the folder `~/.cache/torch/hub/facebookresearch_dinov2_main`
> 
> https://docs.pytorch.org/docs/stable/hub.html#:~:text=pytorch/vision%3A0.10%E2%80%99-,force_reload%20(bool%2C%20optional)%20%E2%80%93%20whether%20to%20discard%20the%20existing%20cache%20and%20force%20a%20fresh%20download.%20Default%20is%20False.,-skip_validation%20(bool

issue resolved 👍 . I guess it was some environment clog. used new environment.
