### ISSUE TITLE
Running with only iBOT loss?

### ISSUE THREAD

**Issue by josephcappadona** [facebookresearch/dinov2#346]
Is the code (supposed to be) structured in a way that allows for training with only iBOT? I've been trying this but have been running into issues, for example, sections like [this](https://github.com/facebookresearch/dinov2/blob/2302b6bf46953431b969155307b9bed152754069/dinov2/train/ssl_meta_arch.py#L169-L225) make me think that the code was designed to always use the DINO loss with only the iBOT loss being optional.

Any clarification would be helpful, thank you!

**Comment by TimDarcet** [comment]
Hi,
The code is designed to always use DINO, and optionally use iBOT.

It should not be too hard to modify the code to use only iBOT without DINO. However, in my experience the iBOT loss does not work alone, so your training will probably run into instabilities.
