### ISSUE TITLE
Where is DataAugmentationDino transform being applied to the Images?

### ISSUE THREAD

**Issue by rishit5** [facebookresearch/dinov2#368]
I am trying replicate the pre-training of DINOv2 on my custom dataset. I made by own dataset by extending the 'ExtendedVision' dataset and did all the necessary changes. 

When I run the pre-training using 

`python dinov2/train/train.py \
    --config-file <output-dir> \
    --output-dir <output-dir> \
    train.dataset_path=CustomDataset
`

I can see that the collate_fn is expecting the DataAugmentationDINO transform to be applied to the data. However, the transform does not seem to be applied. 

Can someone confirm where this is being applied?

**Comment by ccharest93** [comment]
https://github.com/facebookresearch/dinov2/blob/2302b6bf46953431b969155307b9bed152754069/dinov2/train/train.py#L175
https://pytorch.org/tutorials/beginner/basics/data_tutorial.html
Its applied to the dataset class, if you have a your own dataset implementation make sure you call with it the DataAugmentationDINO transform
