### ISSUE TITLE
Relation between batch_size_per_gpu and OFFICIAL_EPOCH_LENGTH

### ISSUE THREAD

**Issue by risratna** [facebookresearch/dinov2#376]
Hi, 

I am a bit of a DL noob. 

I am trying to pre-train dinov2 on my custom dataset, and was wondering about the relation between batch_size_per_gpu (which I am setting to 12) and OFFICIAL_EPOCH_LENGTH parameter, which is hard coded to 1250. 

If I reduce the batch_size_per_gpu to 2, then ETA for pretraining reduces to 1 day, whereas, if I increase the batch_size_per_gpu to 64, ETA increases to 8 days. 

In all of this, the OFFICIAL_EPOCH_LENGTH stays the same (1250). 

I wanted to understand, why OFFICIAL_EPOCH_LENGTH is a different parameter? Can't it be calculated as (total_training_samples / batch_size)?

So If I set my OFFICIAL_EPOCH_LENGTH to 1250 and batch_size_per_gpu to 2, does this mean that it is using 1250 * 2 = 2500 training samples no matter how large my training dataset is?

Any help is appreciated

**Comment by qasfb** [comment]
OFFICIAL_EPOCH_LENGTH is just a value to describe the arbitrary unit "epoch" into a number of training iterations.
batch_size_per_gpu is just the batch size per GPU at each iteration. Your understanding is correct !
