### ISSUE TITLE
Extend to input a sequence of frames

### ISSUE THREAD

**Issue by sharmita01** [facebookresearch/dinov2#38]
Hi,
I was wondering if there is an easy way to incorporate a sequence of frames while being able to use the pretrained weights (i.e., w/o retraining the network). I do not aim to have aggregated embeddings of multiple frames by passing each frame independently. I am looking to have native video-level inputs.

Thanks in advance!

**Comment by ccharest93** [comment]
if x is a list of frames that you want to process at the same time,
`x = torch.utils.data.default_collate(x)`
will create a batch of them and you can pass that to the network. However the network will treat it as separate inputs, there is no mechanism in place for information to flow between the frames of sequencial video input

**Comment by sharmita01** [comment]
closing
