### ISSUE TITLE
How do I use DINOv2 to train unlabeled data

### ISSUE THREAD

**Issue by ChenjieXu** [facebookresearch/dinov2#382]
In current training method, dataset is organized in ImageNet format which has label of image. How can I train the model with unlabeled data?

**Comment by maxmal1** [comment]
Labels shouldn't matter in the training stage -- you should be able to get away with arbitrarily assigned labels.

**Comment by ChenjieXu** [comment]
> Labels shouldn't matter in the training stage -- you should be able to get away with arbitrarily assigned labels.

Thank you for your reply. Does that mean I can put all unlabeled images in one folder in train stage?

**Comment by maxmal1** [comment]
Here is a previous issue that is relevant: https://github.com/facebookresearch/dinov2/issues/142

**Comment by ChenjieXu** [comment]
Thank you for providing the information.

**Comment by ayushnangia** [comment]
did you figure out how to just pretrain by initializing the weights from the model weights given? @ChenjieXu

**Comment by csaroff** [comment]
@ayushnangia You could give my fork a shot!

https://github.com/facebookresearch/dinov2/issues/142#issuecomment-1865134558
