### ISSUE TITLE
Getting Different results with each run!!

### ISSUE THREAD

**Issue by benam2** [facebookresearch/dinov2#386]
Hi, and thanks for sharing the model with us.

I am experimenting with DinoV2 model to extract embedding out of it. However, I get VERY different result based on if I download the pretrained model VS if I load the model through torch.hub.

I put a dummy example here, and I hope someone can point me into the right directions:

**1: Loading model from torch.hub**
```
model = torch.hub.load('facebookresearch/dinov2', 'dinov2_vitb14')
transform = transforms.Compose(
    [
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]
        ),
    ])
model.eval()
for i in range(10):
  response = requests.get('https://media.istockphoto.com/id/1472634899/photo/a-mixed-race-senior-woman-holding-her-puppy-outdoors.jpg?s=1024x1024&w=is&k=20&c=pvHKHPzTFgPAv_JKgPKlbUJhIBvgeA5VQflvFII-mss=', stream=True)
  img = Image.open(io.BytesIO(response.content)).convert("RGB")
  net_input = transform(img).unsqueeze(0)
  with torch.no_grad():
    feature = model(net_input).squeeze().numpy()
  logger.info(f'Emb: {feature[:3]}')
```

I this way I always get stable results : 
`Emb: [-0.48145077 -1.8566128  -1.0795641 ]`

**2: Downloading model from this repo and then loading the model**

```
from dinov2.models.vision_transformer import vit_base
import torch
from PIL import Image, ImageOps
from torchvision import transforms
import requests
import io
from loguru import logger

model = torch.load('./dinov2_vitb14_pretrain.pth') 
model = vit_base(
    patch_size=14,
    img_size=526,
    init_values=1.0,
    block_chunks=0)

transform = transforms.Compose(
    [
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]
        ),
    ])
model.eval()
for i in range(10):
  response =  requests.get('[https://someurl/dog.jpg?imbypass=true', stream=True)imbypass=true](https://media.istockphoto.com/id/1472634899/photo/a-mixed-race-senior-woman-holding-her-puppy-outdoors.jpg?s=1024x1024&w=is&k=20&c=pvHKHPzTFgPAv_JKgPKlbUJhIBvgeA5VQflvFII-mss=)', stream=True)
  img = Image.open(io.BytesIO(response.content)).convert("RGB")
  net_input = transform(img).unsqueeze(0)
  with torch.no_grad():
    feature = model(net_input).squeeze().numpy()
  logger.info(f'Emb: {feature[:3]}')
```

I get:
`Emb: [ 1.570992   1.2198048 -0.6719947]`

And the weird part is that when I restart my cluster and run the second code agaian the generated dimension is different.

Any thought on this?

**Comment by benam2** [comment]
Thanks @heyoeyo, my mistake in the code while copy pasting here. 
When I change it to the correct way of loading:

```
state_dict = torch.load('./dinov2_vitb14_pretrain.pth') 

transformer = vit_base(
    patch_size=14,
    img_size=526,
    init_values=1.0,
    block_chunks=0)
transformer.load_state_dict(state_dict, strict=False)
```

it raises: '`dict' object has no attribute 'eval'`


The embedding differences is related to when I ship the model to the MLFLOW. I will post my question later. But do you have any idea why the above code arises when loading the model correctly?

Thanks.
Do you have any idea how to fix this?

**Comment by heyoeyo** [comment]
The error: `'dict' object has no attribute 'eval'` just means that somewhere in the code there's a statement that's trying to call `.eval()` on something that is a dictionary. So almost like doing: `{}.eval()`

In the earlier code, the state dict was loaded into a variable called `model` and then later there is a `model.eval()`, which would produce that kind of error. Changing it to `transformer.eval()` (based on the updated code you posted) should fix it.

**Comment by benam2** [comment]
Thank you so much @heyoeyo ^ ^
