### ISSUE TITLE
Self supervised fine-tuning on custom dataset

### ISSUE THREAD

**Issue by nidoebel** [facebookresearch/dinov2#392]
Is there a way to fine-tune DinoV2 for specific domain using an unlabeled dataset? Since the original model was trained with self supervision I thought this should be possible, but I have not found a way to do it. 

The reason why I have unlabeled datasets is because the embeddings created with the fine-tuneing model should then be used for image similarity search with FAISS. 

Thanks!!

**Comment by qasfb** [comment]
We haven't explored much how to fine-tune using SSL on a custom dataset.
My recommendation would be to run a short dinov2 training, and use one of the pretrained models as initialization, but I don't have a good recipe for that.
