### ISSUE TITLE
Classification and segmentation performance comparing to traditional CNN

### ISSUE THREAD

**Issue by kail85** [facebookresearch/dinov2#4]
Correct me if I was wrong, seems the paper did not mention a performance comparison with other supervised CNN models?

**Comment by patricklabatut** [comment]
Most evaluations are conducted against other compared self-supervised or weakly-supervised models (i.e. OpenCLIP, MAE, DINO, iBOT), which are Transformer-based (with the exception of SEER). Re: comparison against SOTA supervised approaches, there may still be a few that are CNN-based and included in Table 10 for semantic segmentation.

**Comment by patricklabatut** [comment]
Closing as answered.
