### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [facebookresearch/dinov2#40]
Hi there :wave: 

Will the dataset ever be shared?

Thanks a lot

Fra

**Comment by woctezuma** [comment]
Related:
- https://github.com/facebookresearch/dinov2/issues/24#issuecomment-1515477785

**Comment by FrancescoSaverioZuppichini** [comment]
okay, got it - sad since if one would like to do something/better he/she will be force to re introduce the carbion emissions for the dataset creation

**Comment by patricklabatut** [comment]
> re introduce the carbion emissions for the dataset creation

Compared to large pretrainings, the data curation is (overall) much lighter compute-wise and intermediate results are easier to re-use.
