### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by buaa-luzhi** [facebookresearch/dinov2#403]
@patricklabatut
Dear author,  thank you for this wonderful work.
I want to fine-tune my own dataset to extract domain-specific image features.  .So is there a pre-trained model for the student network, rather than training the network from scratch?
Thank you very much. Looking forward to your reply

**Comment by nguyenthekhoig7** [comment]
Hi, as far as I know from the paper and some of the notebook share in the issues, DINOv2 models are pretrained, and can be ultilize by adding (start with) a classification layer at the end, fine tune that layer and you have a model.
