### ISSUE TITLE
The PCA visualization

### ISSUE THREAD

**Issue by xiejingcheng** [facebookresearch/dinov2#412]
Hello, I'm very interested in the PCA visualization shown in your paper. Could you please tell me more about how you created it? If I could receive your response, I would be very happy.

**Comment by tyz1030** [comment]
I have same question here actually, trying to figure out

**Comment by heyoeyo** [comment]
There is a [pull request](https://github.com/facebookresearch/dinov2/pull/187) that includes a demo using PCA. Specifically, it's the single [notebook file](https://github.com/facebookresearch/dinov2/pull/187/files) that is included in that PR. Going through that notebook might help explain the process.

**Comment by xiejingcheng** [comment]
> There is a [pull request](https://github.com/facebookresearch/dinov2/pull/187) that includes a demo using PCA. Specifically, it's the single [notebook file](https://github.com/facebookresearch/dinov2/pull/187/files) that is included in that PR. Going through that notebook might help explain the process.

Thank you very much for your reminder. Under your guidance, I discovered this [branch ](https://github.com/facebookresearch/dinov2/tree/add-features-pca-nb)

**Comment by ApiaoSamaa** [comment]
> There is a [pull request](https://github.com/facebookresearch/dinov2/pull/187) that includes a demo using PCA. Specifically, it's the single [notebook file](https://github.com/facebookresearch/dinov2/pull/187/files) that is included in that PR. Going through that notebook might help explain the process.↳

Thanks a lot! But I'm confused about how to generate the `standard_array`, since I use the dimension of `1024` instead of `768`. 

```python
# Precomputed foreground / background projection
STANDARD_ARRAY_URL = "https://dl.fbaipublicfiles.com/dinov2/arrays/standard.npy"
standard_array = load_array_from_url(STANDARD_ARRAY_URL)
```

**Comment by Woodyet** [comment]
an example exists here - https://github.com/salihmarangoz/dinov2/blob/main/notebooks/matching_example/dinov2_matching.ipynb 
that doesn't require the standard map just feed in a mask of white if you want the whole image
