### ISSUE TITLE
[Feature Request] ViT Backbone on Segment Anything Dataset

### ISSUE THREAD

**Issue by jiaxiaosong1002** [facebookresearch/dinov2#42]
Thanks a lot for your efforts to open source the code and checkpoint!!!

Recently, another team from Meta also releases a strong semantic segmentation dataset/model :0 - [SegmentAnything](https://github.com/facebookresearch/segment-anything).

I think a dinov2 ViT backbone finetuned on SegmentAnything would be of great help for the CV community since it combines 
 best self-supervised and supervised model in the world :). Do you guys have any plan to try it and release the backbone weights?  For starter, ViT-Base/Large would be especially accessible for individual/academic researchers to use.

Thanks again for your time!

**Comment by patricklabatut** [comment]
> Do you guys have any plan to try it and release the backbone weights?

The pre-trained DINOv2 backbone weights are available as well as SAM models. Fine-tuning the combination specifically for a SegmentAnything (SAM) segmentation task is not something really in the spirit of our work (re-using the same frozen weights for all the tasks).

But feel free to try replacing / adjusting the SAM backbone with a DINOv2 one and fine-tuning the overall model. And if interesting, don't hesitate to report the results back to us and our colleagues working on SAM!
