### ISSUE TITLE
"inverted" first principal component of vitb14_reg4

### ISSUE THREAD

**Issue by amundra15** [facebookresearch/dinov2#420]
I tried using the vitb model with registers, and it seems like the first principal component behaves differently from the model without registers.

Input RGB:
![input(1)](https://github.com/facebookresearch/dinov2/assets/30622740/41b22d77-be54-4991-8d72-3b8eb2ddf934)

PCA(n=1) of patch tokens of vitb14:
![dino_fgbg](https://github.com/facebookresearch/dinov2/assets/30622740/d058ae64-4b42-4b96-b90d-f105964a0cb8)

PCA(n=1) of patch tokens of vitb14_reg4:
![dino_reg4_fgbg](https://github.com/facebookresearch/dinov2/assets/30622740/9989aeca-afa2-436a-aae7-b7643e09c873)

The values are overlayed in red. (ignore the mismatch in the image orientation).

Since this is an emergent behaviour, I don't think it is a problem in itself. But I want to confirm if others have also observed the same behaviour.

**Comment by TheoMoutakanni** [comment]
Hello @amundra15,
This is an expected behaviour of the PCA. The sign of the components can be flipped without changing the decomposition.
You just need to be aware of this phenomenon.
