### ISSUE TITLE
need easy shell cmd to analyze one picture

### ISSUE THREAD

**Issue by shblhy** [facebookresearch/dinov2#43]
This is the function in the official demo. I want to write a piece of python code, then execute a script command, and pass in parameters such as the image address to achieve the same function. How to do it?

https://dinov2.metademolab.com/demos?category=retrieval
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/3368535/233642631-7ffe86e4-1560-4cc6-a4d5-b28fadd0e61b.png">

**Comment by patricklabatut** [comment]
Closing and keeping track as part of #95.
