### ISSUE TITLE
How to finetune on downstream depth estimation task?

### ISSUE THREAD

**Issue by jywu511** [facebookresearch/dinov2#46]
Thanks for sharing your work! I am trying to incorporate your encoder into a depth estimation task, but I haven’t found any relevant code.
The paper said,
```bash
.DPT: we use the DPT decoder (Ranftl et al., 2021) on top of our frozen models and setup a regression task. We scale the size of the head following the dimension of the features for each architecture. We show results for all baselines, all datasets and all setups in Table 11
```
Can you share a simple example to guide me on how to use your encoder for depth estimation? Thanks again.

**Comment by kalyani7195** [comment]
I have the same question as well

**Comment by ccharest93** [comment]
Dept estimation requires training a head on top of the backbone
https://github.com/facebookresearch/dinov2/issues/6#issuecomment-1513785818

**Comment by TheoMoutakanni** [comment]
Hello @jywu511 
You could use something like this to train a depth decoder:
https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox
Just create a new backbone with our DINOv2 model
To iterate faster you could also preprocess all DINOv2 features and save the patch and CLS tokens then only compute the head on top of them during training

**Comment by patricklabatut** [comment]
Closing as answered and to instead use #54 to generally keep track of documentation / training code / model weights needs around depth estimation.
