### ISSUE TITLE
How to get intermediate image features like from Swin Transformers?

### ISSUE THREAD

**Issue by kashyappiyush1998** [facebookresearch/dinov2#48]
When I pass 1024px size and get intermediate image features from Swin Transform I get in return image feature of sizes:

torch.Size([1, 128, 256, 256]) 
torch.Size([1, 128, 256, 256]) 
torch.Size([1, 256, 128, 128]) 
torch.Size([1, 512, 64, 64]) 
torch.Size([1, 1024, 32, 32])

How do I get something like this from dinov2?

**Comment by ccharest93** [comment]
Swin transformer uses non overlapping attention windows with local attention, which is different from this model, this was done to combat the quadratic complexity of increasing the patch numbers resulting from smaller patches.

Using flash attention, this model can directly take the 1024 pixel input which somewhat addresses that issue (patch size is stuck at 14 but allows for higher resolution images).

Now if you want to have local attention within a bigger image, nothing stops you from cropping your image in 4, 9,16...  non overlapping pieces and then feeding these into the network. This would result in local attention within these pieces.

**Comment by woctezuma** [comment]
Related:
- https://github.com/facebookresearch/dinov2/issues/2#issuecomment-1513210404 (`get_intermediate_layers()`)
