### ISSUE TITLE
Merging FSDP's local_state_dict sharded model weights after training

### ISSUE THREAD

**Issue by chokevin8** [facebookresearch/dinov2#487]
Hello, I plan to use the student and teacher's weights of my DINOv2 model (I did the DINOv2 training with FSDP, 2 nodes and 16 GPUs in total (8 GPU per node)) for downstream use for a different distillation training between student and teacher. However, the full model weight that is saved is teacher only (under the eval folder), and the latest checkpoint.pth are model weights that are sharded and saved for each GPU during FSDP. 

So I have model_final.rank_0.pth all the way up to model_final.rank_15.pth, and I'm not sure if there's an implementation that can merge these offline without being in the same environment. I've tried to set up a code to merge these locally without the actual 2 node and 16 GPU environment, but it's not working. Also, when trying to use [accelerate's merge function](https://huggingface.co/docs/accelerate/en/package_reference/fsdp#accelerate.utils.merge_fsdp_weights) merge_fsdp_weights, it says it is missing the .metadata file, which I am suspecting is a metadata file that contains how the model was sharded. Can anyone help me out with this? @TimDarcet @qasfb or anyone who can help me out...? Would really appreciate it, thank you!

**Comment by TimDarcet** [comment]
Hi,

Unsharding a sharded torch FSDPv1 is notoriously annoying, there is no good standard way to do it.
The only "intended" procedure is to allocate 16 gpus again, load the whole sharded model as if you were training it, and unshard it once it's loaded.

In order to go around this I've got this snippet that monkeypatches the ShardedTensor class to allow for loading them locally. It's ugly an provided without guarantees (haven't used it in a while), but it should be what you are looking for.

Best of luck

https://gist.github.com/TimDarcet/8b986c6b2b2522603fe57a4327590652

**Comment by chokevin8** [comment]
@TimDarcet Thank you for your response and sharing the code! I knew they were getting updated but I didn't know there were different FSDP "versions". So in more recent versions of FSDP there is a local implementation of unsharding or merging the sharded weights without having to allocate the same FSDP environment (like 16 gpus in my case)?

Will look into this and update & close this thread if there are any changes that need to be made to the code.

**Comment by chokevin8** [comment]
I've made some edits and I want to share the code that I was successfully able to merge the weights with: 
[](https://gist.github.com/chokevin8/8c70b3e9fa5591b8e618afe6075e2baf
)
Note that I was using a different environment from dinov2's original environment, so you may need to make some edits as well. For your reference I was using torch 2.4.0, CUDA 11.8, python 3.11.10. To run this anti_fsdp_checkpointer.py make sure you load the model as you trained it (regarding model cfg w/ SSLMetaArch) and run the file. 

Hopefully this helps someone out!
