### ISSUE TITLE
"128k prototypes" in Table 1

### ISSUE THREAD

**Issue by Divadi** [facebookresearch/dinov2#66]
Hello, thank you for open sourcing this work. I wanted to ask - in Table 1 comparing iBOT with DINOv2, what is meant by the "128k prototypes"?
![image](https://user-images.githubusercontent.com/17109672/234958646-1443c5d4-f402-464c-b39d-f5d01225277b.png)

Thank you in advance.

**Comment by dillonalaird** [comment]
I believe it's referring to the number of prototypes used in the SwAV algorithm from the "Unsupervised Learning of Visual Features by Contrastive Clustering Assignments" paper https://arxiv.org/abs/2006.09882 the number of prototypes is the size of the C matrix. In Table 12 they experiment up to 100k prototypes which is around the size used in DINOv2.
