### ISSUE TITLE
How to get last self attention ?

### ISSUE THREAD

**Issue by YScheung** [facebookresearch/dinov2#69]
Hi, I would like to know if there's a way to get the last self-attention from DINOv2 ? In DINO, I believe we can do so by blk(x, return_attention=True), but are there similar functions here in DINOv2 ?

Many thanks

**Comment by ccharest93** [comment]
Pytorch allows you to register hooks for nn.module instances, here is a snippet of code you can use to extract attention from a certain layer

```
self.hook_handlers.append(block.attn.attn_drop.register_forward_hook(self._get_hook('attn')))

 def _get_hook(self, facet):
      if facet in ['attn', 'token']:
          def _hook(model, input, output):
              self._feats.append(output)
          return _hook
```

**Comment by YScheung** [comment]
Thank You very much for your help and reply. However, when I tried to extract the qkv and attention values using hooks, they seem to be a bit off. I suspect this has to do with the newly added layer 'LayerScale()' in DINOv2 Block module. I would therefore like to know if this method is still applicable to extracting attention and qkv values or are there any postprocessing needed? Though it might as well be problems in my code.

**Comment by ccharest93** [comment]
I eddited my previous post with the whole hook function , for qkv you need to hook in a different place using something like `self.hook_handlers.append(block.attn.register_forward_hook(self._get_hook(facet)))`
try to find where the values you want to extract are and extract from that place. Ive extracted qkv, attn and tokens with no problem even with the layerscale

**Comment by YScheung** [comment]
Great. Thanks a lot for your help and the code.
