### ISSUE TITLE
3D DINOv2

### ISSUE THREAD

**Issue by ilyanelken** [facebookresearch/dinov2#70]
Hi,

Do you think it is feasible to train DINOv2 on large amounts of structured 3D data?

Thanks,
Ilya

**Comment by woctezuma** [comment]
Related:
- https://github.com/facebookresearch/dinov2/issues/28

**Comment by ilyanelken** [comment]
@woctezuma Thanks, it is related but no the same question. I am asking here if it is possible to ***train*** DINOv2 on 3D images.

**Comment by pierrefdz** [comment]
> @woctezuma Thanks, it is related but no the same question. I am asking here if it is possible to ***train*** DINOv2 on 3D images.

Hi!
I would answer the same as in the previous issue.
https://github.com/facebookresearch/dinov2/issues/28#issuecomment-1515842659

You can train it in 3D images by using the same methods used in video (and changing the patch embedding component).

**Comment by Yuki-Suprise** [comment]
Do you have a completed script please? If so, can you show me how to implement it?
