### ISSUE TITLE
Pretrain on custom dataset

### ISSUE THREAD

**Issue by QasimKhan5x** [facebookresearch/dinov2#72]
I would like to train a small ViT model on CIFAR10 using dinov2, ideally in a Google Colab notebook where only 1 GPU is available. What steps should I follow to do that?

**Comment by woctezuma** [comment]
You could probably follow [this tutorial][colab-tuto] [![Open In Colab][colab-badge]][colab-tuto] for []

Reference:
- https://github.com/NielsRogge/Transformers-Tutorials
- https://github.com/NielsRogge/Transformers-Tutorials/blob/master/VisionTransformer/Fine_tuning_the_Vision_Transformer_on_CIFAR_10_with_the_%F0%9F%A4%97_Trainer.ipynb

[colab-tuto]: <https://colab.research.google.com/github/NielsRogge/Transformers-Tutorials/blob/master/VisionTransformer/Fine_tuning_the_Vision_Transformer_on_CIFAR_10_with_the_%F0%9F%A4%97_Trainer.ipynb>
[colab-badge]: <https://colab.research.google.com/assets/colab-badge.svg>

**Comment by QasimKhan5x** [comment]
I want to use dinov2 to pretrain the vision transformer on CIFAR 10 not finetune it (I know CIFAR 10 isn't an ideal dataset for pretraining, but I would like to experiment with it and check the results). Would you know a tutorial that uses a similar self-supervised learning method on CIFAR 10 or any other (small) dataset?

**Comment by patricklabatut** [comment]
Closing, tracked in #243
