### ISSUE TITLE
Image embeddings extraction example

### ISSUE THREAD

**Issue by SkalskiP** [facebookresearch/dinov2#73]
Hi all 👋🏻! Is there any simple embedding extraction example? I'm interested in something super simple and basic.

1. Load a single image from the local path.
2. Load model.
3. Run the model to extract embeddings. 

I would be very grateful for any help. Kind regards.

**Comment by woctezuma** [comment]
- #2

**Comment by patricklabatut** [comment]
Closing and keeping track in #53.
