### ISSUE TITLE
Is it possible to run under Pytorch 1.xx?

### ISSUE THREAD

**Issue by wang-sj16** [facebookresearch/dinov2#74]
Hi, I'm wondering if it's possible to run DinoV2 under pytorch 1.xx rather than Pytorch2? I'm trying to combine it with other projects but that project failed to run under pytorch 2.0

**Comment by babar414** [comment]
Hi, as per my exp, its possible to use it in older versions of torch but expect to use more memory and compute as the older versions do not support some of the tricks mentioned in the paper. I was able to do linear probing on frozen weights in PyTorch 1.7.0 but I notice two things that need to be considered:

1) the stochastic depth implementation of dino2 would not work in older torch version (may need it if you want to finetune)
2) torch could not load the model weights so I had them saved in numpy while being in torch 2.0 and then read them in the torch 1.7 environment to convert them to .pth format.

There maybe other things you need to consider depending on your target usecase.

**Comment by SimingYan** [comment]
Thank you for your reply! @babar414 ! I just had a quick question. If I were to load the model weights in Torch 1.7, do you think it would be able to generate the same features as Torch 2.0 when taking the same image input?

**Comment by babar414** [comment]
@SimingYan I would assume that since the weights are identical, the output should match. However, to be certain, I would do a sanity check by running the same image through both versions of the model in different environments and compare the output features.

**Comment by MaekTec** [comment]
@babar414 Why does the stochastic depth implementation not work with older Pytorch versions? When I train it with Pytorch 1.10.1, I don't get an error.

**Comment by patricklabatut** [comment]
Closing: we haven't tried / don't support older PyTorch versions and this otherwise got answered by the community.
