### ISSUE TITLE
script used to generate the teaser video

### ISSUE THREAD

**Issue by Tsingularity** [facebookresearch/dinov2#75]
Hi, thanks for the great work and open-sourcing the code!

Just wondering could you please also provide the script to generate the teaser video? It looks really cool and wanna re-produce it on my end. Thanks a lot!

<img width="864" alt="image" src="https://user-images.githubusercontent.com/13026942/235515636-e4355795-50b3-493a-948b-fca848abdd90.png">

**Comment by woctezuma** [comment]
Related:
-  #23

**Comment by patricklabatut** [comment]
Closing as answered.
