### ISSUE TITLE
reuqest Model for semantic segmentation tasks

### ISSUE THREAD

**Issue by hardlipay** [facebookresearch/dinov2#80]
I have carefully studied the [linear head weights] model in redme and the eval/linear.py in the project It seems that the pre-trained weights anyhow need to continue training a linear_classifiers in eval/linear.py, is this the case? Is there a published pre-trained model for the semantic segmentation task?

**Comment by woctezuma** [comment]
- #55

**Comment by patricklabatut** [comment]
We are not publishing the heads or models for semantic segmentation at this time. Closing this task, but we are keeping track of the demand in #55.

**Comment by hardlipay** [comment]
> We are not publishing the heads or models for semantic segmentation at this time. Closing this task, but we are keeping track of the demand in #55.

thanks，got it.keep study

**Comment by patricklabatut** [comment]
We have just added the models and supporting code for semantic segmentation.
