### ISSUE TITLE
about Mask2Former and ViT-Adapter

### ISSUE THREAD

**Issue by HosseinSheikhi** [facebookresearch/dinov2#84]
How did you integrate the ViT model into Mask2Former and ViT-Adapter, taking into account a patch size of 14? Did you use interpolated patch embeddings or modify the SPM module (and maybea few other modules)?

**Comment by pranavraja99** [comment]
@TimDarcet Can we get the code for this by any chance. I am thinking of integrating this into the repo through a PR but would be much simpler if we could see the modifications
