### ISSUE TITLE
pip install cuml-cu11 --extra-index-url=https://pypi.nvidia.com

### ISSUE THREAD

**Issue by DoloresChong** [facebookresearch/dinov2#9]
Why am I unable to install cuml-cu11? I've tried various methods, including accessing https://pypi.nvidia.com/ directly, but I've been denied access due to lack of permissions.
![image](https://user-images.githubusercontent.com/76471389/232760329-8f32ef19-f2af-405e-8670-8af43c2a3eb2.png)

**Comment by yosugahhh** [comment]
use wsl, not windows

**Comment by patricklabatut** [comment]
You seem to be using Windows. We should clarify that the code does expect a Linux environment and has never been tested elsewhere. So the above recommendation to use instead WSL on Windows could indeed help although there is no guarantee this will actually work without more efforts.

Additionally, [conda](https://docs.conda.io/projects/conda/en/stable/) is the recommended way to install the right dependencies for the training and evaluation code. If you nevertherless want to use `pip install`, AFAICT this command line should install the right packages (from an environment with just python 3.9):

```
pip install --extra-index-url https://download.pytorch.org/whl/cu117 --extra-index-url https://pypi.nvidia.com git+https://github.com/facebookresearch/dinov2
```

Or just:

```
pip install -r requirements.txt
```

to not even install the `dinov2` package.

**Comment by DoloresChong** [comment]
> 
Thank you, I think it's very effective

**Comment by DoloresChong** [comment]
Thank you very much for your reminder. I was too careless to notice that the project needs to run on Linux. Thanks again. @patricklabatut
