### ISSUE TITLE
 what is the model "dinov2_vitl14_pretrain.pth" output ?

### ISSUE THREAD

**Issue by xcp2022beGood** [facebookresearch/dinov2#94]
hi friends:
  I load the model "dinov2_vitl14_pretrain.pth" and input a image to see it output , the output of the model is a tensor with a shape of [1,1024] , how can I convert this tensor to a image or somthing else?  I tried a way in my code but a error occured. The code is below.

#################################BEGIN of CODE###############################  
import torch
import torchvision.transforms as transforms
from PIL import Image
from dinov2.models.vision_transformer import DinoVisionTransformer
from dinov2.models.vision_transformer import vit_large 
from torchvision.transforms import ToTensor,ToPILImage   

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = vit_large(
    patch_size=14,
    img_size=526,
    init_values=1.0,
    block_chunks=0
 )
model.load_state_dict(torch.load('dinov2_vitl14_pretrain.pth'))
model.to(device)

img_path = "./image.png"
img = Image.open(img_path)

transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

model.eval()

img_tensor = transform(img)

img_tensor = img_tensor.unsqueeze(0) # the shape of img_tensor is [1,3,224,224]

img_tensor = img_tensor.to(device)

with torch.no_grad():
    outputs = model(img_tensor)   #the shape of outputs is [1,1024] 

######here  I want to see a image output ,so I tried below:

output_img = transforms.ToPILImage()(outputs.cpu()[0])
tensor_to_pil = ToPILImage()
tensor_to_pil(outputs.data.squeeze(0)).show()

import matplotlib.pyplot as plt
plt.imshow(output_img)
plt.show()
#################################END of CODE###############################
the error is here:

---> 54 output_img = transforms.ToPILImage()(outputs.cpu()[0])
ValueError: pic should be 2[/3](https://file+.vscode-resource.vscode-cdn.net/3) dimensional. Got 1 dimensions.

**Comment by patricklabatut** [comment]
The output of this model is an embedding of the input image (ViT-L embed dim = 1024). This vector can for instance be used to search for similar images based on their contents. Or as demonstrated in the `hubconf.py` module, this output can be combined with a (specifically trained) custom head to e.g. build a classifier.

**Comment by dFuong** [comment]
@xcp2022beGood How do you get "**dinov2_vitl14_pretrain.pth**" ?

**Comment by xcp2022beGood** [comment]
> @xcp2022beGood How do you get "**dinov2_vitl14_pretrain.pth**" ?

I download it from the https://github.com/facebookresearch/dinov2. You can see the [README.md](https://github.com/facebookresearch/dinov2#readme) and click the pth file you want to download.

**Comment by dFuong** [comment]
Is that linear classification weight ?

**Comment by woctezuma** [comment]
> Is that linear classification weight ?

No. This is https://github.com/facebookresearch/dinov2#pretrained-models

**Comment by patricklabatut** [comment]
Closing as answered.
