### ISSUE TITLE
The weight updating of student model during knowledge distillation

### ISSUE THREAD

**Issue by XC9292** [facebookresearch/dinov2#96]
The dino_v2 paper states that "keep a spare EMA of the student that we use as our final model".
Does this mean ?
1. You have another spare student model during distillation.
2. At each iteration, one student model updates the weights via distillation loss from frozen teacher model (larger ViT) and, at the meantime, another one stack updated student weights via EMA (which will be the final model). 
Or
1. You only have one student model during distillation.
2. At each iteration, at first, you update the weights of the student models via distillation loss and then, use EMA to update the student model.

**Comment by TheoMoutakanni** [comment]
Hello,
1. & 2. is what we are doing.
The EMA is just used as a final model and doesn't interact with the training scheme. The student is only updated through the distillation loss.

**Comment by XC9292** [comment]
> Hello,
> 
> 1. & 2. is what we are doing.
> 
> The EMA is just used as a final model and doesn't interact with the training scheme. The student is only updated through the distillation loss.
