### ISSUE TITLE
How to implement depth estimation with the provided model

### ISSUE THREAD

**Issue by xcp2022beGood** [facebookresearch/dinov2#97]
Hi everyone:
I load the model dinov2_vitl14_pretrain.pth , I input a image ang got  a  [1 , 1024] tensor ,how to see the effect of depth estimate?

**Comment by patricklabatut** [comment]
One needs to train a depth estimation head on top of the provided backbone (`dinov2_vitl14_pretrain.pth`). We are tracking demand for this in #54.
