### ISSUE TITLE
Extra files for the dataset preparation

### ISSUE THREAD

**Issue by ankitkariryaa** [facebookresearch/dinov2#98]
Hi, 

How to get the extra files such as <ROOT>/labels.txt which are not available in the downloaded imagenet dataset?

```
Data preparation
ImageNet-1k

The root directory of the dataset should hold the following contents:

    <ROOT>/test/ILSVRC2012_test_00000001.JPEG
     ...
    <ROOT>/labels.txt
```

Thanks!

**Comment by ankitkariryaa** [comment]
I created it from LOC_synset_mapping.txt
[labels.txt](https://github.com/facebookresearch/dinov2/files/11473738/labels.txt)

**Comment by woctezuma** [comment]
- #87
