### ISSUE TITLE
Request for Semantic Segmentation Model

### ISSUE THREAD

**Issue by shakeebmurtaza** [facebookresearch/dinov2#99]
Could you please provide the weights of model trained for semantic segmentation task (it would be helpful for for those of us working with semantic segmentation). I believe that many in our community would benefit from this model.

**Comment by patricklabatut** [comment]
Closed, to be tracked in #55.

**Comment by yuyu19970716** [comment]
Hello, I would like to know if the distillation step is not implemented in DINOV2 now? How does distillation work? Another question is, how to implement the training of VIT-Adapter and mask2former? I saw the code, but I didn't know how to modify and train it
